import { motion } from 'motion/react';
import { ArrowRight, Eye, FlaskConical, GraduationCap, Radar, Route, Sparkles } from 'lucide-react';
import { useMemo, useState } from 'react';
import { pedagogicalTracks, type Experience, type TrackKey } from './pedagogical-plan';

const trackIcon:Record<TrackKey,typeof GraduationCap>={didactic:GraduationCap,patch:FlaskConical,acquisition:Radar};
export default function CurriculumMap({onOpenLegacy}:{onOpenLegacy:()=>void}){
 const[track,setTrack]=useState<TrackKey>('didactic');const[selected,setSelected]=useState<Experience>(pedagogicalTracks[0].experiences[0]);
 const current=useMemo(()=>pedagogicalTracks.find(t=>t.key===track)!,[track]);
 const chooseTrack=(key:TrackKey)=>{setTrack(key);const t=pedagogicalTracks.find(x=>x.key===key)!;setSelected(t.experiences[0])};
 const productionRoute=(x:Experience)=>x.id==='D1'?'#wave-lab':x.route;
 const open=(x:Experience)=>{setSelected(x);const route=productionRoute(x);if(route)window.location.hash=route};
 return <div className={`curriculum-map track-${track}`}><header className="curriculum-head"><div><span>HYDROSIM · PEDAGOGICAL CONCEPT MAP</span><h1>Learn through the acquisition chain.</h1><p>The canonical pedagogical plan now drives the concept structure. Inputs and outputs are exposed as visual design material, not scientific implementation.</p></div><button onClick={onOpenLegacy}><Eye size={16}/> Original visual labs</button></header>
 <nav className="track-switcher">{pedagogicalTracks.map(t=>{const Icon=trackIcon[t.key];return <button key={t.key} className={track===t.key?'active':''} onClick={()=>chooseTrack(t.key)}><Icon size={20}/><span><strong>{t.title}</strong><small>{t.experiences.length} experiences · {t.subtitle}</small></span></button>})}</nav>
 <div className="curriculum-workspace"><section className="experience-list"><div className="track-title"><span>{current.key.toUpperCase()}</span><strong>{current.title}</strong><small>{current.subtitle}</small></div><div className="experience-grid">{current.experiences.map(x=><motion.button key={x.id} className={selected.id===x.id?'selected':''} onClick={()=>setSelected(x)} whileHover={{y:-2}}><span>{x.id}</span><strong>{x.title}</strong><small>{x.outputs[0]}</small><ArrowRight size={14}/></motion.button>)}</div></section>
 <aside className="experience-inspector"><div className="experience-id"><span>{selected.id}</span><Sparkles size={16}/></div><h2>{selected.title}</h2><p className="design-cue">{selected.designCue}</p><div className="io-flow"><div><small>INPUTS</small><div className="io-pills">{selected.inputs.map(x=><span key={x}>{x}</span>)}</div></div><Route size={20}/><div><small>LEARNING OUTPUTS / VISUALIZATIONS</small><div className="io-pills output">{selected.outputs.map(x=><span key={x}>{x}</span>)}</div></div></div><div className="concept-loop"><small>CONCEPTUAL INTERACTION LOOP</small><div><span>INPUT</span><i>→</i><strong>MANIPULATE</strong><i>→</i><span>SEE CONSEQUENCE</span></div></div>{productionRoute(selected)?<button className="launch-experience" onClick={()=>open(selected)}><FlaskConical size={16}/> Open current visual foundation</button>:<button className="launch-experience future" disabled><FlaskConical size={16}/> Dedicated concept workspace next</button>}<p className="scope-note">Illustrative design only · equations, ranges, geometry and scientific behavior are intentionally not authoritative here.</p></aside></div>
 </div>
}