export type TrackKey='didactic'|'patch'|'acquisition';
export type Experience={id:string;title:string;inputs:string[];outputs:string[];route?:string;designCue:string};
export type Track={key:TrackKey;title:string;subtitle:string;experiences:Experience[]};

export const pedagogicalTracks:Track[]=[
{key:'didactic',title:'Didactic Module',subtitle:'Understand acquisition phenomena through direct visual experiments',experiences:[
{id:'D1',title:'Acoustic Wave & Frequency',inputs:['wave','frequency','period','wavelength','amplitude','phase'],outputs:['propagating wave','frequency comparison','wavelength comparison'],route:'#signal-lab/waveform',designCue:'A living wave ruler: change frequency and see cycles compress while wavelength markers respond.'},
{id:'D2',title:'Pulse & Signal Processing',inputs:['CW / chirp','frequency','bandwidth','pulse length','envelope','filtering','phase','zero crossing'],outputs:['time waveform','envelope','echo','pulse compression','resolution'],route:'#signal-lab/pulse',designCue:'One pulse travels left-to-right through transmit, echo and processing lenses.'},
{id:'D3',title:'Sonar Equation & Propagation Loss',inputs:['source level','spreading','absorption','frequency','range','noise','SNR'],outputs:['intensity vs range','SNR vs range','frequency effects','detection margin'],route:'#propagation-lab/attenuation',designCue:'An energy budget flows through the water column with a persistent detection-margin horizon.'},
{id:'D4',title:'Sound Speed & Refraction',inputs:['sound speed','SVP','gradients','depth','launch angle'],outputs:['ray tracing','refraction','acoustic path','incorrect-profile comparison'],route:'#propagation-lab/refraction',designCue:'Directly reshape the water profile while baseline and current rays remain overlaid.'},
{id:'D5',title:'Acoustic Detection Fundamentals',inputs:['signal','noise','threshold','SNR'],outputs:['echo quality','detectability'],route:'#integrated-lab/sounding-generation',designCue:'A threshold gate sits between an incoming echo and a visible detection decision.'},
{id:'D6',title:'Transducer & Array Construction',inputs:['elements','frequency','wavelength','spacing','aperture','dimensions','geometry','eccentricity','Mills Cross','shading'],outputs:['array construction','directivity','beamwidth','side lobes','gains / losses'],route:'#beam-lab/beam-pattern',designCue:'Build the array by moving elements; directivity grows beside the physical aperture.'},
{id:'D7',title:'Beamforming & Electronic Steering',inputs:['relative delay / phase','TX / RX','steering','receive timing','dynamic focusing','apodization'],outputs:['beam formation','steering','coherent summation','side lobes','steering losses'],route:'#beam-lab/steering',designCue:'Phase/delay tiles feed a live beam so coherent summation is seen rather than described.'},
{id:'D8',title:'Echosounders — SBES vs MBES',inputs:['SBES / MBES','TX / RX arrays','beam geometry','footprint','depth','incidence','beam spacing'],outputs:['synchronized comparison','footprint','swath','beam spacing','sounding spacing'],route:'#beam-lab/footprint',designCue:'Split-screen synchronized ping: one narrow look versus a full swath over the same bottom.'},
{id:'D9',title:'Bottom Detection',inputs:['amplitude','phase','hybrid mode','window','thresholds','multiple detections','High Density'],outputs:['detection formation','false / missed detections','detection position','signal → sounding','High Density'],route:'#integrated-lab/sounding-generation',designCue:'Turn the return trace into candidate detections, then into accepted soundings.'},
{id:'D10',title:'Multisector MBES',inputs:['sector count','sector angles','frequency / sector','timing sequence','pulse duration','power'],outputs:['sector timeline','geometry','footprints','swaths','frequency-time relation'],route:'#beam-lab/beam-pattern',designCue:'A circular/linear sector sequencer is synchronized with colored conceptual swath sectors.'},
{id:'D11',title:'Vessel & Sensor Configuration',inputs:['vessel dimensions','reference point','sensor positions','orientations','lever arms','transducer','antenna','MRU / IMU','waterline'],outputs:['vessel model','sensor layout','frames / offsets','vessel file concept'],route:'#vessel-lab/vessel',designCue:'The vessel is the editor: drag sensors, expose references and inspect relationships in place.'},
{id:'D12',title:'Vessel Motion',inputs:['roll','pitch','yaw / heading','heave','vessel geometry','sensor locations'],outputs:['vessel / sensor motion','beam displacement','swath effects','sounding effects'],route:'#motion-lab/motion-viewer',designCue:'Motion propagates visually from platform to beam to sounding trail in one causal scene.'},
{id:'D13',title:'PU & Sensor Integration',inputs:['processing unit','sensor types','serial / Ethernet','ports','baud rate','message rates','protocols','time source'],outputs:['PU-sensor diagram','streams','connection state','incompatibilities','configuration-error effects'],route:'#integrated-lab/survey-setup',designCue:'A spatial wiring canvas with animated data streams and visible compatibility states.'},
{id:'D14',title:'Timing, Synchronization & Latency',inputs:['sensor rates','timestamps','clock source','latencies','delays','vessel speed'],outputs:['sensor timeline','synchronization','ping association','temporal → spatial error'],route:'#motion-lab/sounding-impact',designCue:'Stacked sensor timelines converge on each ping; drag latency to see spatial separation emerge.'},
{id:'D15',title:'Sounding Formation',inputs:['TWTT / range','beam angle','position','attitude','lever arms','SV / SVP','timing','vessel configuration'],outputs:['ping → detection → range → transforms → 3D sounding'],route:'#integrated-lab/sounding-generation',designCue:'A single sounding is born step-by-step while every contributing state stays inspectable.'},
{id:'D16',title:'Survey Planning',inputs:['area / DTM','depth','sonar','swath','overlap','line direction','line spacing','speed'],outputs:['planned lines','predicted coverage','gaps / overlap','line count','line length'],route:'#integrated-lab/survey-setup',designCue:'Draw lines directly over the DTM and watch predicted coverage paint underneath them.'},
{id:'D17',title:'Survey Coverage & Acquisition Trade-offs',inputs:['frequency','footprint','beam spacing','High Density','swath','depth','ping rate','speed','multisector','detection configuration'],outputs:['settings → swath → footprints → sounding pattern → coverage','spacing','density','gaps','trade-offs'],route:'#integrated-lab/comparison',designCue:'A synthesis cockpit where changing one acquisition choice ripples through coverage and density.'},
{id:'D18',title:'Uncertainty / TPU',inputs:['position','attitude','range','SV','offset','timing','water level','detection geometry'],outputs:['uncertainty components','THU / TVU / TPU','across-track variation','sounding uncertainty'],route:'#integrated-lab/uncertainty',designCue:'Uncertainty contributors orbit the sounding and expand into an across-track uncertainty field.'}
]},
{key:'patch',title:'Patch Test Module',subtitle:'Plan, acquire, compare and estimate hidden installation biases',experiences:[
{id:'P1',title:'Patch-Test Fundamentals & Error Signatures',inputs:['latency','pitch','roll','heading / yaw biases'],outputs:['characteristic artifacts','error-source distinction'],designCue:'A signature gallery where each hidden bias deforms the same reference surface differently.'},
{id:'P2',title:'Patch-Test Area & Line Planning',inputs:['training DTM','area','line / segment','direction','speed'],outputs:['observability feedback','adequate / suboptimal / inadequate'],designCue:'Draw survey lines directly on a simple DTM; feedback appears as subtle observability cues.'},
{id:'P3',title:'Synthetic Patch-Test Acquisition',inputs:['learner-planned lines','hidden exercise biases'],outputs:['synthetic acquired line pairs','Truth DTM context'],designCue:'Run the planned vessel tracks and leave acquired swath ribbons over the Truth surface.'},
{id:'P4',title:'Manual Patch-Test Calibration',inputs:['line pair','comparison segment','candidate correction'],outputs:['plan / profile / surface overlays','residuals','convergence / divergence'],designCue:'A correction dial updates linked plan, profile and surface comparisons continuously.'},
{id:'P5',title:'Exercise Assessment',inputs:['submitted calibration values'],outputs:['Estimated vs Truth','residual error','performance'],designCue:'Reveal Truth only after submission, with a compact convergence story rather than a score-only screen.'},
{id:'P6',title:'RISC Simulator',inputs:['equivalent system / dataset'],outputs:['RISC diagnosis / estimate','comparison with conventional patch test'],designCue:'Parallel workflow view contrasts RISC and conventional calibration experiences.'}
]},
{key:'acquisition',title:'Acquisition Simulator',subtitle:'Configure and execute a synthetic hydrographic survey',experiences:[
{id:'A1',title:'Survey Area / True Seafloor',inputs:['Truth DTM'],outputs:['Truth seafloor simulation state'],designCue:'A persistent Truth terrain layer anchors every later observation.'},
{id:'A2',title:'Vessel & Installation',inputs:['vessel file','sensor positions','lever arms','alignments','installation'],outputs:['integrated physical platform'],designCue:'Reuse the vessel editor as a loadable installation scene.'},
{id:'A3',title:'Sonar Configuration',inputs:['frequency','pulse','beams','sectors','swath','ping','detection settings'],outputs:['operational sonar state'],designCue:'A compact sonar console whose settings immediately reshape the acquisition preview.'},
{id:'A4',title:'Environment',inputs:['SV / SVP','environment conditions','water level'],outputs:['environment simulation state'],designCue:'Water-column and vertical-reference layers become editable environmental context.'},
{id:'A5',title:'Survey Planning',inputs:['area','lines','direction','spacing','speed','sonar configuration'],outputs:['executable survey plan'],designCue:'Plan lines on the same terrain that will later be acquired.'},
{id:'A6',title:'Acquisition',inputs:['trajectory','installation','sonar','environment','Truth seafloor'],outputs:['integrated sensor / ping / observation simulation'],designCue:'A live survey world connects vessel motion, pings, swath and observation formation.'},
{id:'A7',title:'Synthetic Raw Data Generation',inputs:['internal synthetic observations'],outputs:['synthetic raw data for external processing'],designCue:'End the simulator at a clear export boundary: observations become an external-processing package.'}
]}
];