import { motion, type PanInfo } from 'motion/react';
import { GitCompare, Hand, Layers3, Pause, Play, RotateCcw, SlidersHorizontal, Sparkles, Waves } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

export default function PropagationLab({onBack,focus}:{onBack:()=>void;focus?:string}){
 const[gradient,setGradient]=useState(56);const[range,setRange]=useState(68);const[frequency,setFrequency]=useState(44);const[playing,setPlaying]=useState(true);const[touching,setTouching]=useState(false);
 useEffect(()=>{if(focus==='sound-speed'){setGradient(68);setRange(62);setFrequency(38)}else if(focus==='refraction'){setGradient(78);setRange(74);setFrequency(42)}else if(focus==='attenuation'){setGradient(52);setRange(82);setFrequency(76)}else if(focus==='bottom-interaction'){setGradient(58);setRange(76);setFrequency(48)}},[focus]);
 const bend=useMemo(()=>(gradient-50)*2.2,[gradient]);const rays=[-2,-1,0,1,2];const shapeProfile=(_:PointerEvent,info:PanInfo)=>setGradient(Math.max(15,Math.min(85,Math.round(50+info.offset.x/2.8))));
 const title=focus==='sound-speed'?'Shape the profile and let the water column become the control.':focus==='refraction'?'Follow how the path bends through the same water column.':focus==='attenuation'?'Watch energy fade along the path instead of reading a detached number.':focus==='bottom-interaction'?'Shift attention to where the path meets the seabed.':'Reach into the water column and reshape the path.';
 return <div className={`phenomenon-lab propagation-lab propagation-focus-${focus??'sound-speed'}`}><div className="lab-toolbar"><button className="back-button" onClick={onBack}>← System map</button><div className="lab-breadcrumb"><Layers3 size={17}/><span>Propagation</span><b>/</b><strong>{focus??'water-column'} laboratory</strong></div><div className="lab-toolbar-actions"><span className="concept-chip"><Sparkles size={13}/> illustrative</span><button onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pause':'Play'}</button><button><GitCompare size={16}/> Compare</button></div></div>
 <div className="lab-question"><span>03 · PROPAGATION · {(focus??'sound-speed').toUpperCase()}</span><h1>{title}</h1><p>The selected submodule changes the dominant visual lens while source, profile, path, return and seabed stay connected.</p></div>
 <div className="phenomenon-layout"><aside className="control-surface"><div className="control-title"><SlidersHorizontal size={17}/><strong>Environment controls</strong></div><label>Profile curvature <output>{gradient}%</output><input type="range" min="15" max="85" value={gradient} onChange={e=>setGradient(+e.target.value)}/></label><label>Range <output>{range}%</output><input type="range" min="25" max="100" value={range} onChange={e=>setRange(+e.target.value)}/></label><label>Frequency emphasis <output>{frequency}%</output><input type="range" min="10" max="90" value={frequency} onChange={e=>setFrequency(+e.target.value)}/></label><div className="control-readouts"><div><small>Focus</small><strong>{focus??'Sound speed'}</strong></div><div><small>Gesture</small><strong>{touching?'Shaping':'Ready'}</strong></div><div><small>Range</small><strong>{range} rel.</strong></div><div><small>Loss</small><strong>{frequency>55?'High':'Moderate'}</strong></div></div><button className="reset" onClick={()=>{setGradient(56);setRange(68);setFrequency(44)}}><RotateCcw size={15}/> Reset concept</button></aside>
 <section className="phenomenon-stage propagation-stage"><div className="stage-kicker"><div><small>{focus==='attenuation'?'ENERGY LENS':focus==='bottom-interaction'?'SEABED LENS':'DIRECT WATER COLUMN'}</small><strong>Source → profile → path → seabed</strong></div><span>TOUCH THE PROFILE</span></div><div className="prop-scene"><div className="prop-gesture-hint"><Hand size={14}/> drag the profile handle horizontally</div><div className="prop-surface"/><div className="source-pod"><Waves size={20}/><span>source</span></div>{[0,1,2,3].map(i=><div key={i} className="water-layer" style={{top:`${18+i*17}%`,opacity:.16+i*.04}}><span>layer {i+1}</span></div>)}<svg className="ray-field" viewBox="0 0 1000 520" preserveAspectRatio="none">{rays.map((r,i)=>{const start=500+r*18;const end=500+r*80+(range-60)*3;const control=500+r*50+bend;return <motion.path key={r} d={`M ${start} 72 Q ${control} 260 ${end} 455`} fill="none" strokeWidth={i===2?4:2} className={i===2?'ray-primary':'ray-secondary'} animate={playing?{pathLength:[0,1],opacity:[.35,.9,.35]}:{pathLength:1,opacity:.75}} transition={{duration:2.2+i*.2,repeat:playing?Infinity:0,ease:'easeInOut'}}/>})}</svg><div className={`prop-seabed ${focus==='bottom-interaction'?'focus-hot':''}`}/><div className="return-halo" style={{left:`${50+(range-60)*.28}%`}}/><div className={`loss-meter ${focus==='attenuation'?'focus-hot':''}`}><small>ILLUSTRATIVE ENERGY</small><div><i style={{width:`${Math.max(18,100-frequency*.72)}%`}}/></div><span>source</span><span>return</span></div><div className={`profile-ribbon ${touching?'touching':''}`}><small>PROFILE LENS</small><svg viewBox="0 0 100 260" preserveAspectRatio="none"><path d={`M20 10 Q ${25+gradient*.65} 130 25 250`} fill="none"/></svg><motion.button aria-label="Shape profile" className="profile-drag-handle" drag="x" dragMomentum={false} dragElastic={0} onDragStart={()=>setTouching(true)} onDrag={shapeProfile} onDragEnd={()=>setTouching(false)} style={{left:`${18+gradient*.58}%`}}/><strong>{touching?'shaping profile…':'drag the profile →'}</strong></div></div><div className="causal-strip"><div><small>1 · TOUCH</small><strong>Grab the environment</strong><span>The selected phenomenon remains embedded in the scene.</span></div><div><small>2 · FOLLOW</small><strong>Trace the path</strong><span>The same emission redraws as conditions change.</span></div><div><small>3 · NOTICE</small><strong>{focus==='attenuation'?'Watch energy fade':focus==='bottom-interaction'?'Watch the bottom':'See downstream response'}</strong><span>Consequence never leaves the visual field.</span></div></div></section></div></div>
}