import { AlertTriangle, ArrowLeft, GitCompare, Languages, RotateCcw, Waves } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Lang = 'en' | 'pt';
type Scenario = 'constant' | 'layered' | 'comparison';
type Layer = { top_depth_m:number; bottom_depth_m:number; sound_speed_mps:number };
type Segment = { layer_index:number; start_depth_m:number; end_depth_m:number; sound_speed_mps:number; angle_from_vertical_deg:number; horizontal_distance_m:number; path_length_m:number; travel_time_seconds:number; ray_parameter_seconds_per_m:number };
type Ray = { start_depth_m:number; target_depth_m:number; launch_angle_deg_from_vertical:number; ray_parameter_seconds_per_m:number; horizontal_distance_m:number; path_length_m:number; travel_time_seconds:number; segments:Segment[] };
type Response = { reference_ray:Ray; profile_comparison:null|{ reference:Ray; processing:Ray; horizontal_endpoint_error_m:number; depth_endpoint_error_m:number; path_length_difference_m:number; travel_time_difference_seconds:number }; metadata:Record<string,string|number> };

const copy={
 en:{back:'System map',title:'Bend the ray by changing the water column.',sub:'A canonical layered-ray model turns profile structure into path, angle and travel-time consequences.',configured:'Configured',derived:'Derived',truth:'Reference / Truth',angle:'Launch angle',layer2:'Lower-layer sound speed',processing:'Processing-profile sound speed',constant:'Constant sound speed',layered:'Two-layer refraction',comparison:'Wrong processing profile',reset:'Reset',loading:'Solving canonical ray…',retry:'Retry',distance:'Horizontal distance',path:'Path length',time:'Travel time',parameter:'Ray parameter',error:'Endpoint error',reference:'Reference path',processed:'Reconstructed path',boundary:'Idealized 2-D, downward, piecewise-constant layers. No turning rays, multipath or silent profile extrapolation.',cause:'INPUT → PROFILE → REFRACTED ANGLES → PATH / TIME',explainConstant:'Equal sound speed in both layers keeps a straight ray.',explainLayered:'A sound-speed step changes the refracted angle while the canonical ray parameter remains conserved.',explainComparison:'The same reference travel time is reconstructed with a different Configured processing profile.'},
 pt:{back:'Mapa do sistema',title:'Curve o raio alterando a coluna d’água.',sub:'Um modelo canônico em camadas transforma a estrutura do perfil em consequências de trajetória, ângulo e tempo de viagem.',configured:'Configurado',derived:'Derivado',truth:'Referência / Verdade',angle:'Ângulo de lançamento',layer2:'Velocidade do som na camada inferior',processing:'Velocidade do perfil de processamento',constant:'Velocidade do som constante',layered:'Refração em duas camadas',comparison:'Perfil de processamento incorreto',reset:'Redefinir',loading:'Calculando raio canônico…',retry:'Tentar novamente',distance:'Distância horizontal',path:'Comprimento da trajetória',time:'Tempo de viagem',parameter:'Parâmetro do raio',error:'Erro no ponto final',reference:'Trajetória de referência',processed:'Trajetória reconstruída',boundary:'Modelo idealizado 2-D, descendente e em camadas constantes. Sem raios de retorno, multipercurso ou extrapolação silenciosa do perfil.',cause:'ENTRADA → PERFIL → ÂNGULOS REFRATADOS → TRAJETÓRIA / TEMPO',explainConstant:'Velocidade igual nas duas camadas mantém a trajetória retilínea.',explainLayered:'Um salto de velocidade do som altera o ângulo refratado enquanto o parâmetro canônico do raio permanece conservado.',explainComparison:'O mesmo tempo de viagem de referência é reconstruído com um perfil de processamento Configurado diferente.'}
};

function points(ray:Ray){let x=0;const pts:[[number,number]]=[[0,ray.start_depth_m]];for(const s of ray.segments){x+=s.horizontal_distance_m;pts.push([x,s.end_depth_m]);}return pts;}
function polyline(ray:Ray,maxX:number,maxDepth:number){return points(ray).map(([x,z])=>`${40+(x/Math.max(maxX,1))*500},${35+(z/Math.max(maxDepth,1))*390}`).join(' ');}

export default function RefractionLab({onBack}:{onBack:()=>void}){
 const[lang,setLang]=useState<Lang>('en');const[scenario,setScenario]=useState<Scenario>('layered');const[angle,setAngle]=useState(30);const[layer2,setLayer2]=useState(1520);const[processing,setProcessing]=useState(1490);const[data,setData]=useState<Response|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(false);const[nonce,setNonce]=useState(0);const t=copy[lang];
 const request=useMemo(()=>{const lower=scenario==='constant'?1500:layer2;const reference_profile:Layer[]=[{top_depth_m:0,bottom_depth_m:50,sound_speed_mps:1500},{top_depth_m:50,bottom_depth_m:150,sound_speed_mps:lower}];return{launch_angle_deg_from_vertical:angle,start_depth_m:0,target_depth_m:100,reference_profile,processing_profile:scenario==='comparison'?[{top_depth_m:0,bottom_depth_m:50,sound_speed_mps:1500},{top_depth_m:50,bottom_depth_m:150,sound_speed_mps:processing}]:null}},[scenario,angle,layer2,processing]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch('/api/v1/pedagogical/refraction',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request),signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error((await r.json()).detail??`HTTP ${r.status}`);return r.json()}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(String(e.message??e))}).finally(()=>setLoading(false));return()=>controller.abort()},[request,nonce]);
 const reference=data?.reference_ray;const reconstructed=data?.profile_comparison?.processing;const maxX=Math.max(reference?.horizontal_distance_m??1,reconstructed?.horizontal_distance_m??1)*1.12;const maxDepth=Math.max(reference?.target_depth_m??100,reconstructed?.target_depth_m??100,100)*1.05;const explanation=scenario==='constant'?t.explainConstant:scenario==='layered'?t.explainLayered:t.explainComparison;
 return <div className="refraction-lab">
  <header className="refraction-toolbar"><button onClick={onBack}><ArrowLeft size={16}/>{t.back}</button><div><Waves size={18}/><strong>PED-D4 · Sound Speed & Refraction</strong></div><button onClick={()=>setLang(v=>v==='en'?'pt':'en')}><Languages size={16}/>{lang==='en'?'PT-BR':'EN'}</button></header>
  <section className="refraction-question"><small>PED-D4 · VIRTUAL WATER COLUMN</small><h1>{t.title}</h1><p>{t.sub}</p></section>
  <div className="refraction-layout"><aside className="refraction-controls"><div className="state-label">{scenario==='comparison'?t.truth:t.configured}</div><div className="scenario-tabs"><button className={scenario==='constant'?'active':''} onClick={()=>setScenario('constant')}>{t.constant}</button><button className={scenario==='layered'?'active':''} onClick={()=>setScenario('layered')}>{t.layered}</button><button className={scenario==='comparison'?'active':''} onClick={()=>setScenario('comparison')}>{t.comparison}</button></div>
   <label>{t.angle}<output>{angle}°</output><input aria-label={t.angle} type="range" min="5" max="60" value={angle} onChange={e=>setAngle(+e.target.value)}/></label>
   {scenario!=='constant'&&<label>{t.layer2}<output>{layer2} m/s</output><input aria-label={t.layer2} type="range" min="1460" max="1560" step="2" value={layer2} onChange={e=>setLayer2(+e.target.value)}/></label>}
   {scenario==='comparison'&&<label>{t.processing}<output>{processing} m/s</output><input aria-label={t.processing} type="range" min="1460" max="1560" step="2" value={processing} onChange={e=>setProcessing(+e.target.value)}/></label>}
   <button className="refraction-reset" onClick={()=>{setAngle(30);setLayer2(1520);setProcessing(1490)}}><RotateCcw size={15}/>{t.reset}</button><p className="refraction-boundary">{t.boundary}</p></aside>
   <main className="refraction-stage"><div className="causal-title">{t.cause}</div>{loading&&!data&&<div className="refraction-message">{t.loading}</div>}{error&&<div className="refraction-error"><AlertTriangle size={18}/><span>{error}</span><button onClick={()=>setNonce(v=>v+1)}>{t.retry}</button></div>}{data&&<><div className="water-canvas"><div className="layer-label top">0–50 m · 1500 m/s</div><div className="layer-label bottom">50–150 m · {scenario==='constant'?1500:layer2} m/s</div><div className="layer-interface"/><svg viewBox="0 0 580 460" role="img" aria-label="Canonical layered acoustic ray"><line x1="40" y1="35" x2="40" y2="425" className="depth-axis"/><polyline className="ray-reference" points={polyline(data.reference_ray,maxX,maxDepth)}/>{reconstructed&&<polyline className="ray-processing" points={polyline(reconstructed,maxX,maxDepth)}/>}</svg><div className="ray-legend"><span><i className="reference"/>{t.reference}</span>{reconstructed&&<span><i className="processing"/>{t.processed}</span>}</div></div><p className="refraction-explanation">{explanation}</p><div className="refraction-readouts"><div><small>{t.derived}</small><strong>{t.distance}</strong><output>{data.reference_ray.horizontal_distance_m.toFixed(2)} m</output></div><div><small>{t.derived}</small><strong>{t.path}</strong><output>{data.reference_ray.path_length_m.toFixed(2)} m</output></div><div><small>{t.derived}</small><strong>{t.time}</strong><output>{(data.reference_ray.travel_time_seconds*1000).toFixed(3)} ms</output></div><div><small>{t.derived}</small><strong>{t.parameter}</strong><output>{data.reference_ray.ray_parameter_seconds_per_m.toExponential(3)} s/m</output></div>{data.profile_comparison&&<div className="error-readout"><small>{t.derived}</small><strong>{t.error}</strong><output>Δx {data.profile_comparison.horizontal_endpoint_error_m.toFixed(2)} m · Δz {data.profile_comparison.depth_endpoint_error_m.toFixed(2)} m</output></div>}</div><div className="segment-strip">{data.reference_ray.segments.map(s=><div key={s.layer_index}><small>Layer {s.layer_index+1}</small><strong>{s.angle_from_vertical_deg.toFixed(2)}°</strong><span>{s.sound_speed_mps.toFixed(0)} m/s</span></div>)}</div></>}</main></div>
  {scenario==='comparison'&&<div className="comparison-chip"><GitCompare size={15}/>{t.reference} × {t.processed}</div>}
 </div>
}
