import { motion } from 'motion/react';
import { Anchor, Box, Cpu, GitCompare, Radio, RotateCcw, Satellite, Ship, SlidersHorizontal, Sparkles } from 'lucide-react';
import { useState } from 'react';

export default function VesselLab({ onBack }: { onBack: () => void }) {
  const [waterline, setWaterline] = useState(52);
  const [lever, setLever] = useState(35);
  const [draft, setDraft] = useState(46);
  const [explode, setExplode] = useState(false);
  return <div className="phenomenon-lab vessel-lab">
    <div className="lab-toolbar"><button className="back-button" onClick={onBack}>← System map</button><div className="lab-breadcrumb"><Ship size={17}/><span>Vessel & Sensors</span><b>/</b><strong>Reference geometry laboratory</strong></div><div className="lab-toolbar-actions"><span className="concept-chip"><Sparkles size={13}/> illustrative</span><button onClick={()=>setExplode(v=>!v)}><Box size={16}/> {explode?'Assemble':'Explode view'}</button><button><GitCompare size={16}/> Compare</button></div></div>
    <div className="lab-question"><span>04 · VESSEL & SENSORS</span><h1>Make every sensor and reference level physically obvious.</h1><p>Inspect the vessel as a transparent instrument: platform, GNSS, IMU, transducer, lever arms, waterline and vertical references share one scene.</p></div>
    <div className="phenomenon-layout">
      <aside className="control-surface"><div className="control-title"><SlidersHorizontal size={17}/><strong>Geometry controls</strong></div><label>Waterline <output>{waterline}%</output><input type="range" min="35" max="70" value={waterline} onChange={e=>setWaterline(+e.target.value)}/></label><label>Lever-arm exaggeration <output>{lever}%</output><input type="range" min="10" max="80" value={lever} onChange={e=>setLever(+e.target.value)}/></label><label>Draft emphasis <output>{draft}%</output><input type="range" min="20" max="75" value={draft} onChange={e=>setDraft(+e.target.value)}/></label><div className="sensor-key"><div><Satellite size={15}/><span>GNSS antenna</span></div><div><Cpu size={15}/><span>IMU</span></div><div><Radio size={15}/><span>Transducer</span></div><div><Anchor size={15}/><span>VRP / origin</span></div></div><button className="reset" onClick={()=>{setWaterline(52);setLever(35);setDraft(46);setExplode(false)}}><RotateCcw size={15}/> Reset concept</button></aside>
      <section className="phenomenon-stage vessel-stage"><div className="stage-kicker"><div><small>TRANSPARENT PLATFORM</small><strong>Vessel as a connected sensor system</strong></div><span>SELECT → TRACE → RELATE</span></div><div className="vessel-scene">
        <div className="vessel-water" style={{top:`${waterline}%`}}/><motion.div className="vessel-body" animate={{y:explode?18:0,scale:explode?.94:1}}><div className="hull-shape"/><div className="deck-shape"/><div className="bridge-shape"/><div className="sensor gnss" style={{transform:`translate(${explode?-lever:0}px,${explode?-24:0}px)`}}><Satellite size={18}/><span>GNSS</span></div><div className="sensor imu" style={{transform:`translate(${explode?lever*.2:0}px,${explode?-8:0}px)`}}><Cpu size={17}/><span>IMU</span></div><div className="sensor tx" style={{transform:`translate(${explode?lever*.55:0}px,${explode?24:0}px)`}}><Radio size={17}/><span>TX/RX</span></div><div className="vrp"><i/><span>VRP</span></div><div className="lever-line horizontal" style={{width:`${90+lever*2}px`}}/><div className="lever-line vertical" style={{height:`${70+lever}px`}}/></motion.div>
        <div className="vertical-stack"><div className="datum-line chart"><span>chart / reference level</span></div><div className="datum-line water" style={{top:`${waterline}%`}}><span>waterline</span></div><div className="datum-line keel" style={{top:`${waterline+draft*.45}%`}}><span>transducer reference</span></div></div><div className="geometry-callout"><small>GEOMETRY STORY</small><strong>Where is the measurement actually made?</strong><span>Hover/selection concept: illuminate the path from antenna and IMU through the vessel reference point to the acoustic head.</span></div>
      </div><div className="causal-strip"><div><small>1 · LOCATE</small><strong>See the sensors</strong><span>Nothing important is hidden behind a settings form.</span></div><div><small>2 · CONNECT</small><strong>Trace lever arms</strong><span>Relationships are drawn directly on the vessel.</span></div><div><small>3 · REFERENCE</small><strong>Read vertical levels</strong><span>Waterline and reference planes remain visible in context.</span></div></div></section>
    </div>
  </div>;
}
