import { motion } from 'motion/react';
import { Anchor, Box, Cpu, GitCompare, Radio, RotateCcw, Satellite, Ship, SlidersHorizontal, Sparkles } from 'lucide-react';
import { useEffect, useState } from 'react';

type Sensor='gnss'|'imu'|'tx'|'vrp';
const stories:Record<Sensor,{title:string,copy:string}>={gnss:{title:'Position enters here',copy:'Trace the position source toward the common vessel reference.'},imu:{title:'Attitude enters here',copy:'See motion sensing as part of the same connected measurement geometry.'},tx:{title:'The acoustic measurement starts here',copy:'Keep the acoustic head physically tied to the platform references.'},vrp:{title:'Relationships meet here',copy:'Use a visible origin to explain how sensor locations relate to one another.'}};
export default function VesselLab({onBack,focus}:{onBack:()=>void;focus?:string}){
 const[waterline,setWaterline]=useState(52);const[lever,setLever]=useState(35);const[draft,setDraft]=useState(46);const[explode,setExplode]=useState(false);const[selected,setSelected]=useState<Sensor>('tx');
 useEffect(()=>{setWaterline(52);setDraft(46);setExplode(false);if(focus==='gnss')setSelected('gnss');else if(focus==='imu')setSelected('imu');else if(focus==='transducer')setSelected('tx');else if(focus==='lever-arms'){setSelected('vrp');setExplode(true)}else if(focus==='vertical-references'){setSelected('vrp');setWaterline(58);setDraft(52)}else setSelected('tx')},[focus]);
 const sensor=(key:Sensor,cls:string,Icon:any,label:string,style?:React.CSSProperties)=><button className={`sensor ${cls} ${selected===key?'selected':''}`} style={style} onClick={()=>setSelected(key)}><Icon size={17}/><span>{label}</span></button>;
 const title=focus==='gnss'?'Trace position from antenna into the vessel reference geometry.':focus==='imu'?'Place motion sensing inside the same physical reference story.':focus==='lever-arms'?'Make sensor relationships visible as geometry, not numbers.':focus==='vertical-references'?'Stack waterline, transducer and reference levels in one view.':focus==='vessel'?'See the vessel as the instrument that connects everything.':'Touch a sensor and reveal its place in the measurement chain.';
 return <div className={`phenomenon-lab vessel-lab vessel-focus-${focus??'vessel'}`}><div className="lab-toolbar"><button className="back-button" onClick={onBack}>← System map</button><div className="lab-breadcrumb"><Ship size={17}/><span>Vessel & Sensors</span><b>/</b><strong>{focus??'reference geometry'} laboratory</strong></div><div className="lab-toolbar-actions"><span className="concept-chip"><Sparkles size={13}/> illustrative</span><button onClick={()=>setExplode(v=>!v)}><Box size={16}/> {explode?'Assemble':'Explode view'}</button><button><GitCompare size={16}/> Compare</button></div></div>
 <div className="lab-question"><span>04 · VESSEL & SENSORS · {(focus??'vessel').toUpperCase()}</span><h1>{title}</h1><p>The selected submodule changes which part of the transparent instrument is emphasized while the full platform remains visible.</p></div>
 <div className="phenomenon-layout"><aside className="control-surface"><div className="control-title"><SlidersHorizontal size={17}/><strong>Geometry controls</strong></div><label>Waterline <output>{waterline}%</output><input type="range" min="35" max="70" value={waterline} onChange={e=>setWaterline(+e.target.value)}/></label><label>Lever-arm exaggeration <output>{lever}%</output><input type="range" min="10" max="80" value={lever} onChange={e=>setLever(+e.target.value)}/></label><label>Draft emphasis <output>{draft}%</output><input type="range" min="20" max="75" value={draft} onChange={e=>setDraft(+e.target.value)}/></label><div className="sensor-key"><button className={selected==='gnss'?'active':''} onClick={()=>setSelected('gnss')}><Satellite size={15}/>GNSS antenna</button><button className={selected==='imu'?'active':''} onClick={()=>setSelected('imu')}><Cpu size={15}/>IMU</button><button className={selected==='tx'?'active':''} onClick={()=>setSelected('tx')}><Radio size={15}/>Transducer</button><button className={selected==='vrp'?'active':''} onClick={()=>setSelected('vrp')}><Anchor size={15}/>VRP / origin</button></div><button className="reset" onClick={()=>{setWaterline(52);setLever(35);setDraft(46);setExplode(false);setSelected('tx')}}><RotateCcw size={15}/> Reset concept</button></aside>
 <section className="phenomenon-stage vessel-stage"><div className="stage-kicker"><div><small>{focus==='vertical-references'?'VERTICAL STACK':focus==='lever-arms'?'RELATIONSHIP LENS':'SELECTABLE PLATFORM'}</small><strong>Sensor → relationship → reference</strong></div><span>TOUCH → TRACE → UNDERSTAND</span></div><div className={`vessel-scene sensor-focus-${selected}`}><div className="vessel-water" style={{top:`${waterline}%`}}/>{focus==='vertical-references'&&<div className="vertical-reference-ladder"><span>REFERENCE LEVEL</span><i/><span>WATERLINE</span><i/><span>VESSEL ORIGIN</span><i/><span>TRANSDUCER</span></div>}<motion.div className="vessel-body" animate={{y:explode?18:0,scale:explode?.94:1}} transition={{type:'spring',stiffness:100,damping:16}}><div className="hull-shape"/><div className="deck-shape"/><div className="bridge-shape"/>{sensor('gnss','gnss',Satellite,'GNSS',{transform:`translate(${explode?-lever:0}px,${explode?-24:0}px)`})}{sensor('imu','imu',Cpu,'IMU',{transform:`translate(${explode?lever*.2:0}px,${explode?-8:0}px)`})}{sensor('tx','tx',Radio,'TX/RX',{transform:`translate(${explode?lever*.55:0}px,${explode?24:0}px)`})}<button className={`vrp ${selected==='vrp'?'selected':''}`} onClick={()=>setSelected('vrp')}><i/><span>VRP</span></button><div className="lever-line horizontal" style={{width:`${90+lever*2}px`}}/><div className="lever-line vertical" style={{height:`${70+lever}px`}}/>{focus==='lever-arms'&&<><div className="lever-tag horizontal-tag">Δ horizontal</div><div className="lever-tag vertical-tag">Δ vertical</div></>}<motion.div className="reference-pulse" animate={{scale:[.4,2.4],opacity:[.8,0]}} transition={{duration:1.8,repeat:Infinity}}/></motion.div><div className="vertical-stack"><div className="datum-line chart"><span>chart / reference level</span></div><div className="datum-line water" style={{top:`${waterline}%`}}><span>waterline</span></div><div className="datum-line keel" style={{top:`${waterline+draft*.45}%`}}><span>transducer reference</span></div></div><div className="geometry-callout"><small>SELECTED · {selected.toUpperCase()}</small><strong>{focus==='vertical-references'?'Read the vertical story from top to bottom':stories[selected].title}</strong><span>{focus==='vertical-references'?'Keep every level in the same visual stack so the learner can compare relationships directly.':stories[selected].copy}</span></div></div><div className="causal-strip"><div><small>1 · TOUCH</small><strong>Select a physical sensor</strong><span>The vessel itself is the navigation surface.</span></div><div><small>2 · TRACE</small><strong>Illuminate relationships</strong><span>Lever arms and references become contextual.</span></div><div><small>3 · REFERENCE</small><strong>Relate it vertically</strong><span>Reference planes stay around the same object.</span></div></div></section></div></div>
}