import { Activity, RotateCcw, Waves } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Locale='en'|'pt-BR';
type TraceSeries={x:number[];y:number[];x_unit:string;y_unit:string};
type WaveResponse={period_seconds:number;wavelength_m:number;temporal_waveform:TraceSeries;spatial_waveform:TraceSeries;range_offset_m:number|null;metadata:Record<string,number|string>};

const API_BASE=(import.meta.env.VITE_HYDROSIM_API_BASE as string|undefined)??'http://127.0.0.1:8000';
const copy={
 en:{back:'← System map',kicker:'PED-D1 · ACOUSTIC WAVE & FREQUENCY',title:'Change frequency and watch time and space respond together.',subtitle:'The same canonical wave model drives period, wavelength and both linked views.',frequency:'Frequency',soundSpeed:'Sound speed',phase:'Initial phase',amplitude:'Normalized amplitude',time:'Wave in time',space:'Wave in space',period:'Period',wavelength:'Wavelength',configured:'CONFIGURED',derived:'DERIVED',retry:'Retry',unavailable:'Scientific API unavailable',reset:'Reset'},
 'pt-BR':{back:'← Mapa do sistema',kicker:'PED-D1 · ONDA ACÚSTICA E FREQUÊNCIA',title:'Altere a frequência e veja tempo e espaço responderem juntos.',subtitle:'O mesmo modelo canônico determina período, comprimento de onda e as duas visualizações ligadas.',frequency:'Frequência',soundSpeed:'Velocidade do som',phase:'Fase inicial',amplitude:'Amplitude normalizada',time:'Onda no tempo',space:'Onda no espaço',period:'Período',wavelength:'Comprimento de onda',configured:'CONFIGURADO',derived:'DERIVADO',retry:'Tentar novamente',unavailable:'API científica indisponível',reset:'Redefinir'}
} as const;

function path(series:TraceSeries|undefined,width=760,height=190){if(!series||series.x.length<2||series.x.length!==series.y.length)return'';const minX=Math.min(...series.x),maxX=Math.max(...series.x),minY=Math.min(...series.y),maxY=Math.max(...series.y);const dx=maxX-minX||1,dy=maxY-minY||1;return series.x.map((x,i)=>`${i?'L':'M'} ${(((x-minX)/dx)*width).toFixed(2)} ${(height-((series.y[i]-minY)/dy)*height).toFixed(2)}`).join(' ')}
function Trace({series,label}:{series?:TraceSeries;label:string}){const d=useMemo(()=>path(series),[series]);return <div className="wave-trace"><div><strong>{label}</strong><span>{series?.x_unit??''}</span></div><svg viewBox="0 0 760 190" preserveAspectRatio="none"><path className="wave-axis" d="M0 95H760"/><path className="wave-line" d={d}/></svg></div>}

export default function WaveLab({onBack}:{onBack:()=>void}){
 const[locale,setLocale]=useState<Locale>('en');const[frequency,setFrequency]=useState(200);const[soundSpeed,setSoundSpeed]=useState(1500);const[phase,setPhase]=useState(0);const[amplitude,setAmplitude]=useState(1);const[data,setData]=useState<WaveResponse|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState(false);const t=copy[locale];
 useEffect(()=>{const controller=new AbortController();const timer=window.setTimeout(async()=>{setLoading(true);setError(false);try{const r=await fetch(`${API_BASE}/api/v1/pedagogical/wave-kinematics`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({frequency_khz:frequency,sound_speed_mps:soundSpeed,normalized_amplitude:amplitude,initial_phase_rad:phase,sample_count:320,display_cycles:2,snapshot_time_fraction_of_period:0}),signal:controller.signal});if(!r.ok)throw new Error(String(r.status));setData(await r.json())}catch(e){if((e as Error).name!=='AbortError')setError(true)}finally{setLoading(false)}},100);return()=>{controller.abort();window.clearTimeout(timer)}},[frequency,soundSpeed,phase,amplitude]);
 const reset=()=>{setFrequency(200);setSoundSpeed(1500);setPhase(0);setAmplitude(1)};
 return <main className="wave-lab"><header className="wave-toolbar"><button onClick={onBack}>{t.back}</button><span>HydroSIM / PED-D1</span><div><button className={locale==='en'?'active':''} onClick={()=>setLocale('en')}>EN</button><button className={locale==='pt-BR'?'active':''} onClick={()=>setLocale('pt-BR')}>PT-BR</button></div></header><section className="wave-question"><span>{t.kicker}</span><h1>{t.title}</h1><p>{t.subtitle}</p></section><div className="wave-layout"><aside className="wave-controls"><div className="wave-control-title"><Activity size={17}/><strong>{t.configured}</strong></div><label>{t.frequency}<output>{frequency} kHz</output><input type="range" min="20" max="700" step="10" value={frequency} onChange={e=>setFrequency(+e.target.value)}/></label><label>{t.soundSpeed}<output>{soundSpeed} m/s</output><input type="range" min="1400" max="1600" step="5" value={soundSpeed} onChange={e=>setSoundSpeed(+e.target.value)}/></label><label>{t.amplitude}<output>{amplitude.toFixed(1)}</output><input type="range" min="0" max="1" step="0.1" value={amplitude} onChange={e=>setAmplitude(+e.target.value)}/></label><label>{t.phase}<output>{phase.toFixed(2)} rad</output><input type="range" min="-3.14" max="3.14" step="0.1" value={phase} onChange={e=>setPhase(+e.target.value)}/></label><button className="wave-reset" onClick={reset}><RotateCcw size={15}/>{t.reset}</button>{loading&&<small className="wave-status">Updating…</small>}{error&&<button className="wave-error" onClick={()=>setFrequency(v=>v)}>{t.unavailable} · {t.retry}</button>}</aside><section className="wave-stage"><div className="wave-cause-strip"><div><small>{t.configured}</small><strong>{frequency} kHz</strong><span>f</span></div><i>→</i><div><small>{t.derived}</small><strong>{data?(data.period_seconds*1e6).toFixed(2):'—'} µs</strong><span>{t.period}</span></div><i>→</i><div><small>{t.derived}</small><strong>{data?data.wavelength_m.toFixed(4):'—'} m</strong><span>{t.wavelength}</span></div></div><div className="wave-canvas"><Trace series={data?.temporal_waveform} label={t.time}/><div className="wave-link"><Waves size={18}/><span>same canonical wave / mesma onda canônica</span></div><Trace series={data?.spatial_waveform} label={t.space}/></div></section></div></main>
}
