import { expect, test } from '@playwright/test';

const ray={start_depth_m:0,target_depth_m:100,launch_angle_deg_from_vertical:30,ray_parameter_seconds_per_m:0.0003333,horizontal_distance_m:58.2,path_length_m:115.4,travel_time_seconds:0.0764,segments:[{layer_index:0,start_depth_m:0,end_depth_m:50,sound_speed_mps:1500,angle_from_vertical_deg:30,horizontal_distance_m:28.9,path_length_m:57.7,travel_time_seconds:0.0385,ray_parameter_seconds_per_m:0.0003333},{layer_index:1,start_depth_m:50,end_depth_m:100,sound_speed_mps:1520,angle_from_vertical_deg:30.47,horizontal_distance_m:29.3,path_length_m:57.7,travel_time_seconds:0.0379,ray_parameter_seconds_per_m:0.0003333}]};

const sweep=[0,10,20,30,40,50,60].map((angle,index)=>({launch_angle_deg_from_vertical:angle,reference_horizontal_endpoint_m:index*12,processing_horizontal_endpoint_m:index*12-index*.25,processing_depth_endpoint_m:100-index*.05,horizontal_endpoint_error_m:-index*.25,depth_endpoint_error_m:-index*.05}));

test.beforeEach(async({page})=>{await page.addInitScript(()=>sessionStorage.setItem('hydrosim-language','en'))});

test('PED-D4 connects c(z), Truth ray, Processing ray, endpoint displacement and across-swath consequence',async({page})=>{const requests:Array<Record<string,unknown>>=[];await page.route('**/api/v1/pedagogical/refraction',async route=>{const body=route.request().postDataJSON();requests.push(body);const processing={...ray,target_depth_m:98.7,horizontal_distance_m:56.9};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({reference_ray:ray,profile_comparison:body.processing_profile?{reference:ray,processing,horizontal_endpoint_error_m:-1.3,depth_endpoint_error_m:-1.3,path_length_difference_m:-1.1,travel_time_difference_seconds:0}:null,error_sweep:body.processing_profile?sweep:null,metadata:{ray_outputs_state:'Derived'}})});});await page.goto('/#refraction-lab');await expect(page.locator('.lesson-location').getByText('D4',{exact:true})).toBeVisible();await expect(page.getByTestId('d4-connected-scene')).toBeVisible();await expect(page.getByTestId('truth-profile')).toHaveAttribute('points',/\d/);await expect(page.getByTestId('truth-ray')).toHaveAttribute('points',/\d/);await expect(page.getByText('Truth endpoint x',{exact:true})).toBeVisible();expect(requests[0].processing_profile).toBeNull();await page.getByRole('button',{name:'3 · Profile mismatch'}).click();await expect.poll(()=>requests.length).toBeGreaterThan(1);expect(requests.at(-1)?.processing_profile).not.toBeNull();await expect(page.getByTestId('processing-profile')).toHaveAttribute('points',/\d/);await expect(page.getByTestId('processing-ray')).toHaveAttribute('points',/\d/);await expect(page.getByTestId('endpoint-error-vector')).toBeVisible();await expect(page.getByText(/Δx -1.30 m/).first()).toBeVisible();await expect(page.getByTestId('d4-error-sweep')).toBeVisible();const truthBefore=await page.getByTestId('truth-ray').getAttribute('points');const processingSlider=page.getByRole('slider',{name:'Processing-profile sound speed'});await processingSlider.press('ArrowRight');await expect.poll(()=>requests.length).toBeGreaterThan(2);await expect(page.getByTestId('truth-ray')).toHaveAttribute('points',truthBefore??'');await page.getByRole('button',{name:'Mudar idioma para português'}).click();await expect(page.getByRole('button',{name:'3 · Divergência de perfil'})).toBeVisible();await expect(page.getByText('Δ do ponto',{exact:true})).toBeVisible();await expect(page.getByText('Consequência ao longo da faixa',{exact:true})).toBeVisible();});
