"""Dynamic acoustic acquisition infrastructure.

The acquisition public API models geometry, transducers, propagation, waveform,
beamforming, timing, beam spacing, bottom detection, numerical resolution, and
footprint formation. Bottom backscatter belongs to the separate sonar-equation/
demonstration layer.
"""

from .angular_pattern_2d import AngularPattern2DSample, AngularPattern2DScan, scan_mills_cross_two_way_pattern_2d, sensor_angular_direction
from .array_factor import ArrayFactorElementContribution, ArrayFactorResponse, array_factor
from .beam_pattern import AcrossTrackBeamPatternSample, AcrossTrackBeamPatternScan, OneWayBeamPatternResponse, across_track_direction, one_way_beam_pattern, scan_across_track_beam_pattern
from .beam_spacing import BeamSteeringPlan, make_equiangular_beam_plan, make_equidistant_beam_plan
from .beamforming import ReceiveElementSteeringDelay, ReceiveSteeringEvaluation, ReceiveSteeringHypothesis, evaluate_receive_steering, ideal_receive_steering, ideal_receive_steering_from_sound_speed_measurement
from .bottom_detection import BeamDetections, BottomDetection, DetectionMethod, detect_bottom_from_matched_filter
from .element_factor import RectangularElementFactor, rectangular_element_factor
from .element_signals import CoherentReceiveSum, NarrowbandReceiveTone, ReceiveElementPhasor, coherent_receive_sum
from .footprint import FlatSeafloorFootprintModel, InsonifiedFootprint, estimate_flat_seafloor_footprint
from .footprint_contribution import FootprintContributionCell, RefractedFootprintContribution, assess_refracted_footprint_convergence, weight_refracted_footprint_by_matched_filter
from .generation import generate_acquisition_sequence
from .geometric_phase_ramp import GeometricPhaseRamp, GeometricPhaseRampSample, PhaseRampConvergenceDiagnostic, build_geometric_phase_ramp, compare_geometric_phase_ramp_refinement, detect_bottom_from_geometric_phase_ramp, ideal_split_aperture_differential_phase
from .layered_propagation import LayeredRayClosureDiagnostic, LayeredRayPath, LayeredRaySegment, LayeredSoundSpeedProfile, SoundSpeedLayer, assess_layered_ray_time_depth_closure, trace_layered_ray_for_travel_time, trace_layered_ray_to_depth
from .layered_sound_speed_processing import LayeredReconstructionInitialDirection, LayeredSoundSpeedAtTransducerSounding, reconstruct_layered_sound_speed_sounding_from_sonar_state, resolve_layered_reconstruction_initial_direction
from .layered_sound_speed_reference_experiment import LayeredSoundSpeedErrorIsolationMatrix, LayeredSoundSpeedReferenceExperiment, run_layered_sound_speed_error_isolation_matrix, run_layered_sound_speed_reference_experiment
from .models import AcquisitionPing, AcquisitionSequence, PingSchedule
from .multibeam_fan import MillsCrossMultibeamFan, MultibeamFanBeam, MultibeamFanMatrixSample, simulate_mills_cross_multibeam_fan
from .numerical_resolution import AngularGridResolution, DomainSemantics, FootprintConvergenceDiagnostic, ResolutionAxis, SamplingAdequacy, ScalarConvergenceDiagnostic, angular_grid_resolution, assess_baseband_sampling, compare_refracted_footprint_refinement, compare_scalar_refinement
from .pattern_beamwidth import MillsCrossFootprintBeamwidths, PatternDerivedFootprint, PrincipalPlaneBeamwidth, derive_mills_cross_footprint_beamwidths, derive_principal_plane_beamwidth, estimate_mills_cross_pattern_footprint
from .pattern_footprint_2d import MatchedFilterWeightedEquivalentArea, ProjectedPatternCell, ProjectedPatternIllumination, PulseGatedEquivalentArea, gate_projected_pattern_by_rectangular_pulse, project_angular_pattern_to_flat_seafloor, weight_projected_pattern_by_matched_filter
from .phase_detection import PhaseDetectionResult, PhaseRampFit, detect_bottom_from_phase_ramp, detect_bottom_from_sampled_phase, differential_phase
from .phase_detection_convergence import PhaseDetectionConvergenceDiagnostic, compare_geometric_phase_detection_refinement
from .refracted_pattern_footprint import RefractedPatternIllumination, RefractedProjectedPatternCell, project_angular_pattern_through_layered_profile
from .receive_beam_bank import ReceiveBeamBankResponse, ReceiveBeamResponse, evaluate_mills_cross_receive_beam_bank
from .reception import ArrayElementTruthArrival, ArrayTruthReception, simulate_truth_array_reception
from .returns import BeamTruthReturn, ConstantSoundSpeedPropagation, simulate_truth_beam_return
from .sector_signal_chain import SectorSignalChainPing, SectorSignalChainResult, SectorWaveformAssignment, SectorWaveformPlan, simulate_sector_waveform_propagation_ping
from .sound_speed_at_transducer import PrincipalPlaneReceiveAngleEstimate, PrincipalPlaneSteeringTruthComparison, SteeringTruthComparison, compare_principal_plane_steering_with_truth, compare_steering_direction_with_truth, estimate_principal_plane_receive_angle
from .sound_speed_processing import SoundSpeedAtTransducerSource, SoundSpeedAtTransducerUse, use_manual_sound_speed_at_transducer, use_measured_sound_speed_at_transducer
from .sound_speed_profile_boundary import ProfileBoundarySource, SoundSpeedProfileBoundary, profile_boundary_from_profile, profile_boundary_from_sound_speed_at_transducer
from .sound_speed_reference_experiment import SoundSpeedAtTransducerReferenceExperiment, run_sound_speed_at_transducer_reference_experiment
from .sound_speed_sensor import SoundSpeedAtTransducerMeasurement, SoundSpeedSensorAtTransducer, measure_sound_speed_at_transducer
from .sounding_observation import ConstantSoundSpeedRangeObservation, DetectedAcousticObservation, acoustic_observation_from_detection, interpret_observation_constant_sound_speed
from .sounding_reconstruction import ConstantSoundSpeedSounding, LayeredSoundSpeedSounding, reconstruct_constant_sound_speed_sounding, reconstruct_layered_sound_speed_sounding, reconstruct_layered_sound_speed_sounding_from_initial_direction
from .split_aperture import CenterElementPolicy, SplitApertureDefinition, SplitAperturePhaseCenters, SplitApertureResponse, SplitAxis, SubapertureCoherentSum, split_aperture_phase_centers, split_coherent_receive_sum
from .transmission_loss import OneWayTransmissionLoss, PropagationLossModel, ReciprocalTransmissionLoss, one_way_transmission_loss, reciprocal_transmission_loss
from .transmit_beamforming import TransmitElementSteeringDelay, TransmitSteeringLaw, ideal_transmit_steering
from .transmit_sectors import TransmitSector, TransmitSectorSet, make_uniform_transmit_sectors
from .two_way_pattern import TwoWayBeamPatternResponse, two_way_beam_pattern, two_way_beam_pattern_sensor_frame
from .waveform import ContinuousWavePulse, LinearFMPulse, MatchedFilterSummary, WaveformAutocorrelation, matched_filter, sample_cw_baseband, sample_lfm_baseband, sample_waveform_baseband, waveform_autocorrelation, waveform_sampling_adequacy

__all__ = [name for name in globals() if not name.startswith("_")]
