"""Sound-speed-at-transducer effects at the array boundary.

HydroSIM keeps transmit and receive semantics distinct.

Transmit steering:
    the sonar uses ``c_used`` to impose an inter-element delay law; simulation Truth
    uses the actual local sound speed ``c_true`` to determine the physical launch
    direction produced by that law.

Receive angle estimation:
    the physical arriving wavefront is generated by Truth using ``c_true``; the sonar
    maps the observed tangential slowness back to an estimated direction using only
    ``c_used``. The real sonar never needs access to ``c_true``.
"""

from __future__ import annotations

from math import asin, pi, sin, sqrt

from pydantic import BaseModel, ConfigDict, Field, FiniteFloat

from hydrosim.geometry import Vector3


class SteeringTruthComparison(BaseModel):
    """Truth-side physical direction produced by a sonar TX steering law."""

    model_config = ConfigDict(frozen=True)

    configured_direction_array_frame: Vector3
    physical_direction_array_frame: Vector3
    sound_speed_used_by_sonar_mps: FiniteFloat = Field(gt=0.0)
    true_local_sound_speed_mps: FiniteFloat = Field(gt=0.0)
    imposed_tangential_slowness_x_seconds_per_m: FiniteFloat
    imposed_tangential_slowness_y_seconds_per_m: FiniteFloat


class PrincipalPlaneSteeringTruthComparison(BaseModel):
    """Principal-plane TX steering consequence in simulation Truth."""

    model_config = ConfigDict(frozen=True)

    configured_angle_rad: FiniteFloat
    sound_speed_used_by_sonar_mps: FiniteFloat = Field(gt=0.0)
    true_local_sound_speed_mps: FiniteFloat = Field(gt=0.0)
    imposed_tangential_slowness_seconds_per_m: FiniteFloat
    physical_angle_rad: FiniteFloat
    angle_error_rad: FiniteFloat


class PrincipalPlaneReceiveAngleEstimate(BaseModel):
    """Sonar receive-angle estimate generated from a physical arriving wavefront."""

    model_config = ConfigDict(frozen=True)

    physical_arrival_angle_rad: FiniteFloat
    true_local_sound_speed_mps: FiniteFloat = Field(gt=0.0)
    sound_speed_used_by_sonar_mps: FiniteFloat = Field(gt=0.0)
    observed_tangential_slowness_seconds_per_m: FiniteFloat
    estimated_angle_rad: FiniteFloat
    estimation_error_rad: FiniteFloat


def _validate_sound_speeds(sound_speed_used_by_sonar_mps: float, true_local_sound_speed_mps: float) -> tuple[float, float]:
    sonar_c = float(sound_speed_used_by_sonar_mps)
    true_c = float(true_local_sound_speed_mps)
    if sonar_c <= 0.0:
        raise ValueError("sound_speed_used_by_sonar_mps must be positive")
    if true_c <= 0.0:
        raise ValueError("true_local_sound_speed_mps must be positive")
    return sonar_c, true_c


def compare_principal_plane_steering_with_truth(
    *,
    configured_angle_rad: float,
    sound_speed_used_by_sonar_mps: float,
    true_local_sound_speed_mps: float,
) -> PrincipalPlaneSteeringTruthComparison:
    """Resolve the physical TX angle produced by a sonar steering law."""

    angle = float(configured_angle_rad)
    if not (-0.5 * pi < angle < 0.5 * pi):
        raise ValueError("configured steering angle must satisfy -pi/2 < angle < pi/2")
    sonar_c, true_c = _validate_sound_speeds(sound_speed_used_by_sonar_mps, true_local_sound_speed_mps)
    imposed_slowness = sin(angle) / sonar_c
    physical_sine = imposed_slowness * true_c
    if abs(physical_sine) >= 1.0:
        raise ValueError("sonar steering law is non-propagating at the true local sound speed")
    physical_angle = asin(physical_sine)
    return PrincipalPlaneSteeringTruthComparison(
        configured_angle_rad=angle,
        sound_speed_used_by_sonar_mps=sonar_c,
        true_local_sound_speed_mps=true_c,
        imposed_tangential_slowness_seconds_per_m=imposed_slowness,
        physical_angle_rad=physical_angle,
        angle_error_rad=physical_angle - angle,
    )


def estimate_principal_plane_receive_angle(
    *,
    physical_arrival_angle_rad: float,
    true_local_sound_speed_mps: float,
    sound_speed_used_by_sonar_mps: float,
) -> PrincipalPlaneReceiveAngleEstimate:
    """Estimate receive angle from the physical wavefront under the sonar's ``c_used``.

    Truth determines the observable tangential slowness

        p_t = sin(theta_physical) / c_true.

    Processing maps that observable to its angle estimate using

        sin(theta_estimated) = c_used * p_t.

    ``c_true`` appears here only because HydroSIM is generating the physical
    observation for a controlled simulation diagnostic; it is not an input a real
    sonar would know.
    """

    physical_angle = float(physical_arrival_angle_rad)
    if not (-0.5 * pi < physical_angle < 0.5 * pi):
        raise ValueError("physical arrival angle must satisfy -pi/2 < angle < pi/2")
    sonar_c, true_c = _validate_sound_speeds(sound_speed_used_by_sonar_mps, true_local_sound_speed_mps)
    observed_slowness = sin(physical_angle) / true_c
    estimated_sine = observed_slowness * sonar_c
    if abs(estimated_sine) >= 1.0:
        raise ValueError("physical arrival slowness cannot be represented by the sonar sound speed")
    estimated_angle = asin(estimated_sine)
    return PrincipalPlaneReceiveAngleEstimate(
        physical_arrival_angle_rad=physical_angle,
        true_local_sound_speed_mps=true_c,
        sound_speed_used_by_sonar_mps=sonar_c,
        observed_tangential_slowness_seconds_per_m=observed_slowness,
        estimated_angle_rad=estimated_angle,
        estimation_error_rad=estimated_angle - physical_angle,
    )


def compare_steering_direction_with_truth(
    *,
    configured_direction_array_frame: Vector3,
    sound_speed_used_by_sonar_mps: float,
    true_local_sound_speed_mps: float,
) -> SteeringTruthComparison:
    """Resolve the physical 3-D TX direction produced by a sonar steering law."""

    sonar_c, true_c = _validate_sound_speeds(sound_speed_used_by_sonar_mps, true_local_sound_speed_mps)
    ux = float(configured_direction_array_frame.x)
    uy = float(configured_direction_array_frame.y)
    uz = float(configured_direction_array_frame.z)
    norm = sqrt(ux * ux + uy * uy + uz * uz)
    if abs(norm - 1.0) > 1e-9:
        raise ValueError("configured_direction_array_frame must be a unit vector")
    if uz <= 0.0:
        raise ValueError("configured_direction_array_frame must point toward +Z/down from the array")

    px = ux / sonar_c
    py = uy / sonar_c
    physical_x = true_c * px
    physical_y = true_c * py
    tangential_squared = physical_x * physical_x + physical_y * physical_y
    if tangential_squared >= 1.0:
        raise ValueError("sonar 3-D steering law is non-propagating at the true local sound speed")
    physical_z = sqrt(1.0 - tangential_squared)
    return SteeringTruthComparison(
        configured_direction_array_frame=configured_direction_array_frame,
        physical_direction_array_frame=Vector3(x=physical_x, y=physical_y, z=physical_z),
        sound_speed_used_by_sonar_mps=sonar_c,
        true_local_sound_speed_mps=true_c,
        imposed_tangential_slowness_x_seconds_per_m=px,
        imposed_tangential_slowness_y_seconds_per_m=py,
    )
