import React, { useEffect, useState } from 'react';
import ReactDOM from 'react-dom/client';
import { ChevronRight } from 'lucide-react';
import App from './App';
import CurriculumMap from './CurriculumMap';
import WaveLab from './WaveLab';
import SignalLab from './SignalLab';
import SonarEquationLab from './SonarEquationLab';
import RefractionLab from './RefractionLab';
import BeamLab from './BeamLab';
import ArrayDirectivityLab from './ArrayDirectivityLab';
import BeamformingLab from './BeamformingLab';
import EchosounderLab from './EchosounderLab';
import BottomDetectionLab from './BottomDetectionLab';
import PropagationLab from './PropagationLab';
import VesselLab from './VesselLab';
import MotionLab from './MotionLab';
import IntegratedLab from './IntegratedLab';
import LessonNavigator from './LessonNavigator';
import LessonTransition from './LessonTransition';
import { getHydroLocale, setHydroLocale, useHydroLocale } from './language';
import './styles.css';import './wave-lab.css';import './signal-lab-polish.css';import './sonar-equation-lab.css';import './refraction-lab.css';import './beam-lab.css';import './array-directivity-lab.css';import './beamforming-lab.css';import './bottom-detection-lab.css';import './advanced-labs.css';import './map-polish.css';import './experience-deepening.css';import './curriculum-map.css';import './navigation-enhancements.css';
type View='map'|'legacy'|'wave'|'signal'|'sonar-equation'|'refraction'|'beam'|'array-directivity'|'beamforming'|'echosounder'|'bottom-detection'|'propagation'|'vessel'|'motion'|'integrated';type Route={view:View;focus?:string};
const lessonId:Partial<Record<View,string>>={wave:'D1',signal:'D2','sonar-equation':'D3',refraction:'D4','array-directivity':'D6',beamforming:'D7',echosounder:'D8','bottom-detection':'D9'};
const labBase:Record<Exclude<View,'map'|'legacy'|'wave'|'sonar-equation'|'refraction'|'array-directivity'|'beamforming'|'echosounder'|'bottom-detection'>,string>={signal:'signal-lab',beam:'beam-lab',propagation:'propagation-lab',vessel:'vessel-lab',motion:'motion-lab',integrated:'integrated-lab'};
const navigation:Record<Exclude<View,'map'|'legacy'|'wave'|'sonar-equation'|'refraction'|'array-directivity'|'beamforming'|'echosounder'|'bottom-detection'>,Array<[string,string,string]>>={signal:[['waveform','Waveform','CW, chirp and pulse shapes'],['pulse','Pulse','Duration, timing and repetition'],['spectrum','Spectrum','Bandwidth and frequency content'],['compression','Compression','Matched filtering and resolution']],beam:[['beam-pattern','Beam Pattern','Main lobe and sidelobes'],['steering','Steering','Across-track and along-track'],['beamwidth','Beamwidth','Angular coverage'],['footprint','Footprint','Seafloor projection']],propagation:[['sound-speed','Sound Speed','Profile shapes and assumptions'],['refraction','Refraction','Ray bending through the water'],['attenuation','Attenuation','Loss with range and frequency'],['bottom-interaction','Bottom Interaction','Reflection and scattering']],vessel:[['vessel','Vessel','Platform and body geometry'],['transducer','Transducer','Mounting and orientation'],['gnss','GNSS','Antenna position'],['imu','IMU','Motion sensing'],['lever-arms','Lever Arms','Relative sensor offsets'],['vertical-references','Vertical References','Waterline, datum and levels']],motion:[['heave','Heave','Vertical displacement'],['roll','Roll','Longitudinal-axis rotation'],['pitch','Pitch','Transverse-axis rotation'],['yaw','Yaw','Vertical-axis rotation'],['motion-viewer','Motion Viewer','Linked vessel and beam response'],['sounding-impact','Sounding Impact','Visible geometric consequence']],integrated:[['survey-setup','Survey Setup','Mission and environment'],['realtime-view','Realtime View','Linked 2D and 3D simulation'],['sounding-generation','Sounding Generation','Synthetic observation field'],['uncertainty','Uncertainty','Visual source contributions'],['comparison','Comparison','Baseline versus current'],['experiment-presets','Experiment Presets','Curated learning scenes']]};
const navigationPt:Partial<Record<string,Record<string,[string,string]>>>={signal:{waveform:['Forma de onda','CW, chirp e formas de pulso'],pulse:['Pulso','Duração, tempo e repetição'],spectrum:['Espectro','Largura de banda e conteúdo em frequência'],compression:['Compressão','Filtro casado e resolução']},beam:{'beam-pattern':['Padrão de feixe','Lóbulo principal e lóbulos laterais'],steering:['Apontamento','Transversal e longitudinal'],beamwidth:['Largura de feixe','Cobertura angular'],footprint:['Pegada','Projeção no fundo']},propagation:{'sound-speed':['Velocidade do som','Perfis e hipóteses'],refraction:['Refração','Curvatura do raio na água'],attenuation:['Atenuação','Perdas com distância e frequência'],'bottom-interaction':['Interação com o fundo','Reflexão e espalhamento']},vessel:{vessel:['Embarcação','Plataforma e geometria'],transducer:['Transdutor','Montagem e orientação'],gnss:['GNSS','Posição da antena'],imu:['IMU','Sensor de movimento'],'lever-arms':['Lever arms','Offsets relativos dos sensores'],'vertical-references':['Referências verticais','Linha d’água, datum e níveis']},motion:{heave:['Heave','Deslocamento vertical'],roll:['Roll','Rotação no eixo longitudinal'],pitch:['Pitch','Rotação no eixo transversal'],yaw:['Yaw','Rotação no eixo vertical'],'motion-viewer':['Visualizador de movimento','Resposta conjunta de embarcação e feixe'],'sounding-impact':['Impacto na sondagem','Consequência geométrica visível']},integrated:{'survey-setup':['Configuração do levantamento','Missão e ambiente'],'realtime-view':['Visão em tempo real','Simulação 2D e 3D vinculada'],'sounding-generation':['Formação da sondagem','Campo sintético de observações'],uncertainty:['Incerteza','Contribuições visuais das fontes'],comparison:['Comparação','Referência versus atual'],'experiment-presets':['Cenários de experimento','Cenas didáticas pré-configuradas']}};
function resolveRoute():Route{const[lab,focus]=location.hash.replace(/^#/,'').split('/');const map:Record<string,View>={'legacy':'legacy','wave-lab':'wave','signal-lab':'signal','sonar-equation-lab':'sonar-equation','refraction-lab':'refraction','beam-lab':'beam','array-directivity-lab':'array-directivity','beamforming-lab':'beamforming','echosounder-lab':'echosounder','bottom-detection-lab':'bottom-detection','propagation-lab':'propagation','vessel-lab':'vessel','motion-lab':'motion','integrated-lab':'integrated'};return{view:map[lab]??'map',focus}}
function LabNavigator({route}:{route:Route}){const[locale]=useHydroLocale();if(route.view==='map'||route.view==='legacy'||route.view==='wave'||route.view==='sonar-equation'||route.view==='refraction'||route.view==='array-directivity'||route.view==='beamforming'||route.view==='echosounder'||route.view==='bottom-detection')return null;const view=route.view as Exclude<View,'map'|'legacy'|'wave'|'sonar-equation'|'refraction'|'array-directivity'|'beamforming'|'echosounder'|'bottom-detection'>;const items=navigation[view];const active=route.focus??items[0][0];return <aside className="lab-route-nav"><small>{locale==='en'?'VISUAL LAB VIEWS':'VISTAS DO LABORATÓRIO'}</small>{items.map(([key,label,desc])=>{const translated=locale==='pt-BR'?navigationPt[view]?.[key]:undefined;return <button key={key} className={active===key?'active':''} onClick={()=>{location.hash=`#${labBase[view]}/${key}`}}><span><strong>{translated?.[0]??label}</strong><em>{translated?.[1]??desc}</em></span><ChevronRight size={14}/></button>})}</aside>}
function LanguageBridge({route}:{route:Route}){useEffect(()=>{let syncing=false;const decorate=()=>{document.querySelectorAll('button').forEach(button=>{const text=(button.textContent??'').replace(/🇧🇷|🇺🇸/g,'').trim().toUpperCase();if(text==='PT-BR'||text==='EN'){button.classList.add('hydrosim-language-toggle');button.dataset.localeTarget=text==='PT-BR'?'pt-BR':'en'}});if(route.view!=='map'&&route.view!=='legacy'&&!syncing&&getHydroLocale()==='pt-BR'){const button=[...document.querySelectorAll<HTMLButtonElement>('button.hydrosim-language-toggle')].find(b=>b.dataset.localeTarget==='pt-BR');if(button){syncing=true;queueMicrotask(()=>{button.click();syncing=false})}}};const onClick=(event:Event)=>{const button=(event.target as HTMLElement).closest<HTMLButtonElement>('button.hydrosim-language-toggle');if(!button)return;const target=button.dataset.localeTarget;if(target==='pt-BR'||target==='en')setHydroLocale(target)};decorate();document.addEventListener('click',onClick,true);const observer=new MutationObserver(decorate);observer.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>{document.removeEventListener('click',onClick,true);observer.disconnect()}},[route.view]);return null}
function ConceptRuntime(){const[route,setRoute]=useState<Route>(resolveRoute());useEffect(()=>{const sync=()=>setRoute(resolveRoute());window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);const back=()=>{location.hash=''};let lab:React.ReactNode=null;if(route.view==='wave')lab=<WaveLab onBack={back}/>;if(route.view==='signal')lab=<SignalLab onBack={back} focus={route.focus}/>;if(route.view==='sonar-equation')lab=<SonarEquationLab onBack={back}/>;if(route.view==='refraction')lab=<RefractionLab onBack={back}/>;if(route.view==='beam')lab=<BeamLab onBack={back} focus={route.focus}/>;if(route.view==='array-directivity')lab=<ArrayDirectivityLab onBack={back}/>;if(route.view==='beamforming')lab=<BeamformingLab onBack={back}/>;if(route.view==='echosounder')lab=<EchosounderLab onBack={back}/>;if(route.view==='bottom-detection')lab=<BottomDetectionLab onBack={back}/>;if(route.view==='propagation')lab=<PropagationLab onBack={back} focus={route.focus}/>;if(route.view==='vessel')lab=<VesselLab onBack={back} focus={route.focus}/>;if(route.view==='motion')lab=<MotionLab onBack={back} focus={route.focus}/>;if(route.view==='integrated')lab=<IntegratedLab onBack={back} focus={route.focus}/>;if(route.view==='map')return <><LanguageBridge route={route}/><CurriculumMap onOpenLegacy={()=>{location.hash='#legacy'}}/></>;if(route.view==='legacy')return <App/>;const id=lessonId[route.view];return <><LanguageBridge route={route}/><LessonTransition key={`${route.view}-${route.focus??''}`}/>{id&&<LessonNavigator currentId={id}/>}<div className={`routed-lab focus-${route.focus??'overview'} ${id?'with-lesson-shell':''}`}>{lab}</div><LabNavigator route={route}/></>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><ConceptRuntime/></React.StrictMode>);
