import React, { useEffect, useState } from 'react';
import ReactDOM from 'react-dom/client';
import { ChevronRight } from 'lucide-react';
import App from './App';
import CurriculumMap from './CurriculumMap';
import WaveLab from './WaveLab';
import SignalLab from './SignalLab';
import SonarEquationLab from './SonarEquationLab';
import RefractionLab from './RefractionLab';
import BeamLab from './BeamLab';
import ArrayDirectivityLab from './ArrayDirectivityLab';
import BeamformingLab from './BeamformingLab';
import EchosounderLab from './EchosounderLab';
import BottomDetectionLab from './BottomDetectionLab';
import MultisectorLab from './MultisectorLab';
import VesselConfigurationLab from './VesselConfigurationLab';
import VesselMotionLab from './VesselMotionLab';
import TimingLab from './TimingLab';
import SoundingFormationLab from './SoundingFormationLab';
import TradeoffLab from './TradeoffLab';
import UncertaintyLab from './UncertaintyLab';
import PropagationLab from './PropagationLab';
import VesselLab from './VesselLab';
import MotionLab from './MotionLab';
import IntegratedLab from './IntegratedLab';
import LessonNavigator from './LessonNavigator';
import LessonTransition from './LessonTransition';
import './styles.css';import './wave-lab.css';import './signal-lab-polish.css';import './sonar-equation-lab.css';import './refraction-lab.css';import './beam-lab.css';import './array-directivity-lab.css';import './beamforming-lab.css';import './bottom-detection-lab.css';import './multisector-lab.css';import './vessel-configuration-lab.css';import './vessel-motion-lab.css';import './timing-lab.css';import './sounding-formation-lab.css';import './tradeoff-lab.css';import './uncertainty-lab.css';import './advanced-labs.css';import './map-polish.css';import './experience-deepening.css';import './curriculum-map.css';
type View='map'|'legacy'|'wave'|'signal'|'sonar-equation'|'refraction'|'beam'|'array-directivity'|'beamforming'|'echosounder'|'bottom-detection'|'multisector'|'vessel-configuration'|'vessel-motion'|'timing'|'sounding-formation'|'tradeoffs'|'uncertainty'|'propagation'|'vessel'|'motion'|'integrated';type Route={view:View;focus?:string};
const lessonId:Partial<Record<View,string>>={wave:'D1',signal:'D2','sonar-equation':'D3',refraction:'D4','array-directivity':'D6',beamforming:'D7',echosounder:'D8','bottom-detection':'D9',multisector:'D10','vessel-configuration':'D11','vessel-motion':'D12',timing:'D14','sounding-formation':'D15',tradeoffs:'D17',uncertainty:'D18'};
type RoutedView=Exclude<View,'map'|'legacy'|'wave'|'sonar-equation'|'refraction'|'array-directivity'|'beamforming'|'echosounder'|'bottom-detection'|'multisector'|'vessel-configuration'|'vessel-motion'|'timing'|'sounding-formation'|'tradeoffs'|'uncertainty'>;
const labBase:Record<RoutedView,string>={signal:'signal-lab',beam:'beam-lab',propagation:'propagation-lab',vessel:'vessel-lab',motion:'motion-lab',integrated:'integrated-lab'};
const navigation:Record<RoutedView,Array<[string,string,string]>>={signal:[['overview','Overview','All signal responses'],['waveform','Waveform','Acoustic waveform in time'],['frequency','Frequency','Instantaneous frequency'],['compression','Matched filter','Pulse-compression response']],beam:[['beam-pattern','Beam Pattern','Main lobe and sidelobes'],['steering','Steering','Across-track and along-track'],['beamwidth','Beamwidth','Angular coverage'],['footprint','Footprint','Seafloor projection']],propagation:[['sound-speed','Sound Speed','Profile shapes and assumptions'],['refraction','Refraction','Ray bending through the water'],['attenuation','Attenuation','Loss with range and frequency'],['bottom-interaction','Bottom Interaction','Reflection and scattering']],vessel:[['vessel','Vessel','Platform and body geometry'],['transducer','Transducer','Mounting and orientation'],['gnss','GNSS','Antenna position'],['imu','IMU','Motion sensing'],['lever-arms','Lever Arms','Relative sensor offsets'],['vertical-references','Vertical References','Waterline, datum and levels']],motion:[['heave','Heave','Vertical displacement'],['roll','Roll','Longitudinal-axis rotation'],['pitch','Pitch','Transverse-axis rotation'],['yaw','Yaw','Vertical-axis rotation'],['motion-viewer','Motion Viewer','Linked vessel and beam response'],['sounding-impact','Sounding Impact','Visible geometric consequence']],integrated:[['survey-setup','Survey Setup','Mission and environment'],['realtime-view','Realtime View','Linked 2D and 3D simulation'],['sounding-generation','Sounding Generation','Synthetic observation field'],['uncertainty','Uncertainty','Visual source contributions'],['comparison','Comparison','Baseline versus current'],['experiment-presets','Experiment Presets','Curated learning scenes']]};
function resolveRoute():Route{const[lab,focus]=location.hash.replace(/^#/,'').split('/');const map:Record<string,View>={'legacy':'legacy','wave-lab':'wave','signal-lab':'signal','sonar-equation-lab':'sonar-equation','refraction-lab':'refraction','beam-lab':'beam','array-directivity-lab':'array-directivity','beamforming-lab':'beamforming','echosounder-lab':'echosounder','bottom-detection-lab':'bottom-detection','multisector-lab':'multisector','vessel-configuration-lab':'vessel-configuration','vessel-motion-lab':'vessel-motion','timing-lab':'timing','sounding-formation-lab':'sounding-formation','tradeoff-lab':'tradeoffs','uncertainty-lab':'uncertainty','propagation-lab':'propagation','vessel-lab':'vessel','motion-lab':'motion','integrated-lab':'integrated'};return{view:map[lab]??'map',focus}}
function LabNavigator({route}:{route:Route}){if(route.view==='map'||route.view==='legacy'||route.view==='wave'||route.view==='sonar-equation'||route.view==='refraction'||route.view==='array-directivity'||route.view==='beamforming'||route.view==='echosounder'||route.view==='bottom-detection'||route.view==='multisector'||route.view==='vessel-configuration'||route.view==='vessel-motion'||route.view==='timing'||route.view==='sounding-formation'||route.view==='tradeoffs'||route.view==='uncertainty')return null;const view=route.view as RoutedView;const items=navigation[view];const active=route.focus??items[0][0];return <aside className="lab-route-nav"><small>VISUAL LAB VIEWS</small>{items.map(([key,label,desc])=><button key={key} className={active===key?'active':''} onClick={()=>{location.hash=`#${labBase[view]}/${key}`}}><span><strong>{label}</strong><em>{desc}</em></span><ChevronRight size={14}/></button>)}</aside>}
function ConceptRuntime(){const[route,setRoute]=useState<Route>(resolveRoute());useEffect(()=>{const sync=()=>setRoute(resolveRoute());window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);const back=()=>{location.hash=''};let lab:React.ReactNode=null;if(route.view==='wave')lab=<WaveLab onBack={back}/>;if(route.view==='signal')lab=<SignalLab onBack={back} focus={route.focus}/>;if(route.view==='sonar-equation')lab=<SonarEquationLab onBack={back}/>;if(route.view==='refraction')lab=<RefractionLab onBack={back}/>;if(route.view==='beam')lab=<BeamLab onBack={back} focus={route.focus}/>;if(route.view==='array-directivity')lab=<ArrayDirectivityLab onBack={back}/>;if(route.view==='beamforming')lab=<BeamformingLab onBack={back}/>;if(route.view==='echosounder')lab=<EchosounderLab onBack={back}/>;if(route.view==='bottom-detection')lab=<BottomDetectionLab onBack={back}/>;if(route.view==='multisector')lab=<MultisectorLab onBack={back}/>;if(route.view==='vessel-configuration')lab=<VesselConfigurationLab onBack={back}/>;if(route.view==='vessel-motion')lab=<VesselMotionLab onBack={back}/>;if(route.view==='timing')lab=<TimingLab onBack={back}/>;if(route.view==='sounding-formation')lab=<SoundingFormationLab onBack={back}/>;if(route.view==='tradeoffs')lab=<TradeoffLab onBack={back}/>;if(route.view==='uncertainty')lab=<UncertaintyLab onBack={back}/>;if(route.view==='propagation')lab=<PropagationLab onBack={back} focus={route.focus}/>;if(route.view==='vessel')lab=<VesselLab onBack={back} focus={route.focus}/>;if(route.view==='motion')lab=<MotionLab onBack={back} focus={route.focus}/>;if(route.view==='integrated')lab=<IntegratedLab onBack={back} focus={route.focus}/>;if(route.view==='map')return <CurriculumMap onOpenLegacy={()=>{location.hash='#legacy'}}/>;if(route.view==='legacy')return <App/>;const id=lessonId[route.view];return <><LessonTransition/>{id&&<LessonNavigator currentId={id}/>}<div className={`routed-lab focus-${route.focus??'overview'} ${id?'with-lesson-shell':''}`}>{lab}</div><LabNavigator route={route}/></>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><ConceptRuntime/></React.StrictMode>);
