import { motion, type PanInfo } from 'motion/react';
import { Compass, GitCompare, Hand, Rotate3D, RotateCcw, SlidersHorizontal, Sparkles, Waves } from 'lucide-react';
import { useEffect, useState } from 'react';

function MotionSurveyBoat(){return <svg className="motion-boat-art" viewBox="0 0 360 150" aria-hidden="true"><defs><linearGradient id="motionHull" x1="0" x2="1"><stop offset="0" stopColor="#34475f"/><stop offset=".52" stopColor="#7f91aa"/><stop offset="1" stopColor="#26354a"/></linearGradient><linearGradient id="motionGlass" x1="0" x2="1"><stop offset="0" stopColor="#7ddfff" stopOpacity=".18"/><stop offset="1" stopColor="#c3efff" stopOpacity=".72"/></linearGradient></defs><path className="motion-boat-hull" fill="url(#motionHull)" d="M24 85 L327 85 L295 125 Q184 145 52 122 Z"/><path className="motion-boat-rubrail" d="M29 88 H323"/><path className="motion-boat-deck" d="M78 83 L111 59 H260 L292 83"/><path className="motion-boat-cabin" d="M139 59 L157 30 H231 L252 59 Z"/><path className="motion-boat-window" fill="url(#motionGlass)" d="M163 35 H190 V54 H151 Z M196 35 H225 L242 54 H196 Z"/><path className="motion-boat-mast" d="M195 30 V8 M185 17 H207 M195 8 L207 3"/><circle className="motion-boat-radar" cx="213" cy="4" r="4"/><path className="motion-boat-bow" d="M295 125 Q327 116 342 98"/><path className="motion-boat-sonar" d="M177 132 V146 M164 146 H190"/></svg>}

export default function MotionLab({onBack,focus}:{onBack:()=>void;focus?:string}){
 const[roll,setRoll]=useState(8);const[pitch,setPitch]=useState(-4);const[yaw,setYaw]=useState(12);const[heave,setHeave]=useState(18);const[dragging,setDragging]=useState(false);
 useEffect(()=>{setRoll(0);setPitch(0);setYaw(0);setHeave(0);if(focus==='roll')setRoll(14);else if(focus==='pitch')setPitch(-10);else if(focus==='yaw')setYaw(22);else if(focus==='heave')setHeave(24);else if(focus==='sounding-impact'){setRoll(10);setPitch(-7);setYaw(12);setHeave(16)}else if(focus==='motion-viewer'){setRoll(7);setPitch(-4);setYaw(10);setHeave(12)}},[focus]);
 const gesture=(_:PointerEvent,info:PanInfo)=>{setRoll(Math.max(-20,Math.min(20,Math.round(info.offset.x/9))));setHeave(Math.max(-35,Math.min(35,Math.round(info.offset.y/4))))};
 const title=focus==='roll'?'Roll the vessel and keep the neutral platform visible.':focus==='pitch'?'Pitch becomes the only story that matters for this experiment.':focus==='yaw'?'Rotate heading and watch the geometry shift around the vertical axis.':focus==='heave'?'Move vertically and isolate displacement from rotation.':focus==='sounding-impact'?'Move attention downstream: what changes in the sounding field?':'Move the vessel and watch the whole measurement geometry react.';
 const dominant=focus==='roll'?Math.abs(roll):focus==='pitch'?Math.abs(pitch):focus==='yaw'?Math.abs(yaw):focus==='heave'?Math.abs(heave):Math.max(Math.abs(roll),Math.abs(pitch),Math.abs(yaw),Math.abs(heave));
 return <div className={`phenomenon-lab motion-lab motion-focus-${focus??'motion-viewer'}`}><div className="lab-toolbar"><button className="back-button" onClick={onBack}>← System map</button><div className="lab-breadcrumb"><Rotate3D size={17}/><span>Motion</span><b>/</b><strong>{focus??'platform motion'} laboratory</strong></div><div className="lab-toolbar-actions"><span className="concept-chip"><Sparkles size={13}/> exaggerated</span><button><GitCompare size={16}/> Baseline × Current</button></div></div>
 <div className="lab-question"><span>05 · MOTION · {(focus??'motion-viewer').toUpperCase()}</span><h1>{title}</h1><p>The chosen submodule initializes a dedicated visual experiment while preserving the same vessel, ghost state, beam and sounding field.</p></div>
 <div className="phenomenon-layout"><aside className="control-surface"><div className="control-title"><SlidersHorizontal size={17}/><strong>Motion controls</strong></div><label>Roll <output>{roll}°</output><input type="range" min="-20" max="20" value={roll} onChange={e=>setRoll(+e.target.value)}/></label><label>Pitch <output>{pitch}°</output><input type="range" min="-15" max="15" value={pitch} onChange={e=>setPitch(+e.target.value)}/></label><label>Yaw <output>{yaw}°</output><input type="range" min="-30" max="30" value={yaw} onChange={e=>setYaw(+e.target.value)}/></label><label>Heave <output>{heave} rel.</output><input type="range" min="-35" max="35" value={heave} onChange={e=>setHeave(+e.target.value)}/></label><button className="reset" onClick={()=>{setRoll(0);setPitch(0);setYaw(0);setHeave(0)}}><RotateCcw size={15}/> Zero motion</button></aside>
 <section className="phenomenon-stage motion-stage"><div className="stage-kicker"><div><small>{focus==='sounding-impact'?'DOWNSTREAM LENS':'DIRECT MANIPULATION'}</small><strong>Baseline ghost + current platform</strong></div><span>{focus==='sounding-impact'?'MOVE → TRACE SOUNDINGS':'MOVE → SEE CONSEQUENCE'}</span></div><div className="motion-scene"><div className="motion-gesture-hint"><Hand size={14}/> Drag vessel: horizontal → roll · vertical → heave</div><div className="horizon-line"/><div className="ghost-vessel"><MotionSurveyBoat/><span>baseline</span></div>{focus==='roll'&&<div className="roll-orbit"><i/><span>ROLL ARC</span></div>}{focus==='heave'&&<div className="heave-band"><span>VERTICAL DISPLACEMENT</span></div>}<motion.div className={`current-vessel ${dragging?'dragging':''}`} drag dragMomentum={false} dragElastic={0} onDragStart={()=>setDragging(true)} onDrag={gesture} onDragEnd={()=>setDragging(false)} animate={{rotate:roll,y:heave,x:yaw*.8,skewX:pitch*.35}} transition={{type:'spring',stiffness:90,damping:16}}><MotionSurveyBoat/><div className="motion-axis roll"><Rotate3D size={18}/><span>{focus==='pitch'?'pitch':focus==='yaw'?'yaw':focus==='heave'?'heave':'roll'}</span></div><div className="motion-axis yaw"><Compass size={18}/><span>reference</span></div><div className="motion-beam"><i/><i/><i/><i/><i/></div></motion.div><motion.div className="motion-pulse" animate={{scale:[.5,9],opacity:[.8,0]}} transition={{duration:2,repeat:Infinity}}/><div className="motion-seabed"><span/><span/><span/><span/><span/><span/></div><div className={`sounding-trail ${focus==='sounding-impact'?'focus-hot':''}`}>{Array.from({length:18}).map((_,i)=><motion.i key={i} animate={{x:roll*(i-9)*.28+yaw*.5,y:Math.abs(pitch)*(i%3)*.7+heave*.12}} transition={{type:'spring',stiffness:80,damping:18}}/>)}</div>{focus==='sounding-impact'&&<div className="impact-lens"><small>SOUNDING FIELD LENS</small><strong>{dominant} rel.</strong><span>Visual amplification follows the platform state.</span></div>}<div className="heave-ruler"><Waves size={16}/><span>heave</span><b style={{transform:`translateY(${heave}px)`}}/></div><div className="motion-readout"><small>ACTIVE LENS</small><strong>{dragging?'You are moving the platform':focus??'Motion viewer'}</strong><span>Motion remains exaggerated for learning; this is interaction design, not validated geometry.</span></div></div><div className="causal-strip"><div><small>1 · ISOLATE</small><strong>{focus??'Motion'}</strong><span>Start with a meaningful dedicated state.</span></div><div><small>2 · COMPARE</small><strong>Keep the ghost state</strong><span>The neutral vessel never disappears.</span></div><div><small>3 · FOLLOW</small><strong>Watch beam and soundings</strong><span>Downstream visual elements react in the same scene.</span></div></div></section></div></div>
}