import { useEffect, useMemo, useState } from 'react';
import { RadioTower, RotateCcw, Waves } from 'lucide-react';

type Language='en'|'pt';type Mode='single'|'multi';
type Sector={sector_id:string;centre_across_track_deg:number;across_track_min_deg:number;across_track_max_deg:number;frequency_khz:number;pulse_duration_ms:number;tx_delay_ms:number;relative_power:number};
type ResponseSector=Sector&{sector_index:number;tx_time_s:number;tx_end_time_s:number;wavelength_m:number};
type Response={sectors:ResponseSector[];coverage_supports_deg:[number,number][];transmit_groups:string[][];metadata:Record<string,string|number>};
const initialLanguage=():Language=>sessionStorage.getItem('hydrosim-language')==='pt'?'pt':'en';
const singleSector:Sector={sector_id:'full-swath',centre_across_track_deg:0,across_track_min_deg:-55,across_track_max_deg:55,frequency_khz:300,pulse_duration_ms:.5,tx_delay_ms:0,relative_power:1};
const multiSectors:Sector[]=[
 {sector_id:'port',centre_across_track_deg:35,across_track_min_deg:15,across_track_max_deg:55,frequency_khz:200,pulse_duration_ms:.8,tx_delay_ms:0,relative_power:1},
 {sector_id:'centre',centre_across_track_deg:0,across_track_min_deg:-15,across_track_max_deg:15,frequency_khz:300,pulse_duration_ms:.5,tx_delay_ms:.35,relative_power:1},
 {sector_id:'starboard',centre_across_track_deg:-35,across_track_min_deg:-55,across_track_max_deg:-15,frequency_khz:200,pulse_duration_ms:.8,tx_delay_ms:0,relative_power:1}
];
const copy={
 en:{single:'One TX sector',multi:'Three TX sectors',sector:'TX sector',selected:'Selected TX sector',centre:'Centre',width:'Angular support',frequency:'Frequency',duration:'Pulse duration',delay:'TX delay',coverage:'TX sector geometry',signLegend:'Port + / Starboard −',identity:'TX SECTORS ≠ RX BEAMS',identityLead:'Fixed RX reference behind selectable TX sectors.',baseline:'Single-sector baseline',rxReference:'Conceptual fixed RX fan',current:'Current TX configuration',timing:'Transmit timeline',timingLegend:'Same ping · sector-specific TX epochs',wavelength:'Wavelength',group:'TX group',port:'Port',starboard:'Starboard',simultaneous:'Simultaneous',signal:'Signal configuration',reset:'Reset',compare:'Fixed angular scale · select a TX wedge to edit its support and timing.'},
 pt:{single:'Um setor TX',multi:'Três setores TX',sector:'Setor TX',selected:'Setor TX selecionado',centre:'Centro',width:'Suporte angular',frequency:'Frequência',duration:'Duração do pulso',delay:'Atraso de TX',coverage:'Geometria dos setores TX',signLegend:'Bombordo + / Boreste −',identity:'SETORES TX ≠ FEIXES RX',identityLead:'Referência RX fixa atrás dos setores TX selecionáveis.',baseline:'Referência com um setor',rxReference:'Fan RX fixo conceitual',current:'Configuração TX atual',timing:'Linha do tempo de transmissão',timingLegend:'Mesmo ping · épocas TX específicas por setor',wavelength:'Comprimento de onda',group:'Grupo TX',port:'Bombordo',starboard:'Boreste',simultaneous:'Simultâneo',signal:'Configuração do sinal',reset:'Redefinir',compare:'Escala angular fixa · selecione um setor TX para editar suporte e temporização.'}
};
const clone=(items:Sector[])=>items.map(item=>({...item}));
const ORIGIN_X=360,ORIGIN_Y=42,RADIUS=205;
const point=(deg:number,r=RADIUS)=>{const rad=deg*Math.PI/180;return{x:ORIGIN_X-Math.sin(rad)*r,y:ORIGIN_Y+Math.cos(rad)*r}};
const wedgePath=([minDeg,maxDeg]:[number,number])=>{const a=point(minDeg),b=point(maxDeg);return `M ${ORIGIN_X} ${ORIGIN_Y} L ${a.x.toFixed(2)} ${a.y.toFixed(2)} A ${RADIUS} ${RADIUS} 0 0 0 ${b.x.toFixed(2)} ${b.y.toFixed(2)} Z`};
const arcPath=([minDeg,maxDeg]:[number,number],r=RADIUS)=>{const a=point(minDeg,r),b=point(maxDeg,r);return `M ${a.x.toFixed(2)} ${a.y.toFixed(2)} A ${r} ${r} 0 0 0 ${b.x.toFixed(2)} ${b.y.toFixed(2)}`};
export default function MultisectorLab({onBack:_onBack}:{onBack:()=>void}){
 const[language,setLanguage]=useState<Language>(initialLanguage);const[mode,setMode]=useState<Mode>('single');const[configured,setConfigured]=useState<Sector[]>(()=>clone(multiSectors));const[selectedSectorId,setSelectedSectorId]=useState('centre');const[data,setData]=useState<Response|null>(null);const[error,setError]=useState('');const t=copy[language];
 const sectors=mode==='single'?[singleSector]:configured;
 useEffect(()=>{const sync=(event:Event)=>setLanguage((event as CustomEvent<Language>).detail);window.addEventListener('hydrosim-language-change',sync);return()=>window.removeEventListener('hydrosim-language-change',sync)},[]);
 useEffect(()=>{const controller=new AbortController();setError('');fetch('/api/v1/pedagogical/multisector',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({tx_time_s:10,sound_speed_mps:1500,sectors})}).then(async response=>{if(!response.ok)throw new Error(await response.text());return response.json() as Promise<Response>}).then(setData).catch(reason=>{if(reason.name!=='AbortError')setError(String(reason))});return()=>controller.abort()},[mode,configured]);
 const selectedIndex=Math.max(0,configured.findIndex(sector=>sector.sector_id===selectedSectorId));const selected=configured[selectedIndex]??configured[0];
 const update=(index:number,patch:Partial<Sector>)=>setConfigured(current=>current.map((sector,i)=>i===index?{...sector,...patch}:sector));
 const reset=()=>{setMode('single');setConfigured(clone(multiSectors));setSelectedSectorId('centre')};
 const maxDelay=useMemo(()=>Math.max(...(data?.sectors.map(s=>s.tx_delay_ms+s.pulse_duration_ms)??[1]),1),[data]);const groupFor=(id:string)=>Math.max(0,data?.transmit_groups.findIndex(g=>g.includes(id))??0);
 return <div className="d10-lab"><main className="d10-layout"><aside className="d10-controls">
  <div className="d10-mode-toggle"><button className={mode==='single'?'active':''} onClick={()=>setMode('single')}>{t.single}</button><button className={mode==='multi'?'active':''} onClick={()=>setMode('multi')}>{t.multi}</button></div>
  {mode==='multi'&&selected&&<section className="d10-sector-controls"><h3>{t.selected} · {selected.sector_id}</h3>
   <label>{t.centre}<strong>{selected.centre_across_track_deg.toFixed(0)}°</strong><input type="range" min="-60" max="60" step="5" value={selected.centre_across_track_deg} onChange={e=>{const centre=+e.target.value,half=(selected.across_track_max_deg-selected.across_track_min_deg)/2;update(selectedIndex,{centre_across_track_deg:centre,across_track_min_deg:centre-half,across_track_max_deg:centre+half})}}/></label>
   <label>{t.width}<strong>{(selected.across_track_max_deg-selected.across_track_min_deg).toFixed(0)}°</strong><input type="range" min="10" max="60" step="5" value={selected.across_track_max_deg-selected.across_track_min_deg} onChange={e=>{const half=+e.target.value/2;update(selectedIndex,{across_track_min_deg:selected.centre_across_track_deg-half,across_track_max_deg:selected.centre_across_track_deg+half})}}/></label>
   <label>{t.delay}<strong>{selected.tx_delay_ms.toFixed(2)} ms</strong><input type="range" min="0" max="1.5" step="0.05" value={selected.tx_delay_ms} onChange={e=>update(selectedIndex,{tx_delay_ms:+e.target.value})}/></label>
   <details className="d10-signal-details"><summary>{t.signal}</summary><label>{t.frequency}<strong>{selected.frequency_khz.toFixed(0)} kHz</strong><input type="range" min="100" max="500" step="25" value={selected.frequency_khz} onChange={e=>update(selectedIndex,{frequency_khz:+e.target.value})}/></label><label>{t.duration}<strong>{selected.pulse_duration_ms.toFixed(2)} ms</strong><input type="range" min="0.1" max="2" step="0.05" value={selected.pulse_duration_ms} onChange={e=>update(selectedIndex,{pulse_duration_ms:+e.target.value})}/></label></details>
  </section>}<button type="button" className="d10-reset" onClick={reset}><RotateCcw size={15}/>{t.reset}</button></aside>
  <section className="d10-stage">{error?<div className="d10-message">{error}</div>:<><div className="d10-identity"><strong>{t.identity}</strong><span>{t.identityLead}</span></div><div className="d10-panel"><div className="d10-panel-title"><RadioTower size={18}/><div><small>{t.coverage}</small><strong>{t.signLegend.toUpperCase()}</strong></div></div>
   <svg className="d10-sector-scene" viewBox="0 0 720 300" role="img" aria-label={`${t.coverage}. ${t.rxReference}. ${t.current}: ${mode==='single'?t.single:t.multi}`} style={{width:'100%',minHeight:260}}>
    <line x1={ORIGIN_X} y1={ORIGIN_Y} x2={ORIGIN_X} y2={270} stroke="currentColor" strokeOpacity=".18" strokeDasharray="4 6"/>
    {[-50,-40,-30,-20,-10,0,10,20,30,40,50].map(angle=>{const p=point(angle,190);return <line key={`rx-${angle}`} x1={ORIGIN_X} y1={ORIGIN_Y} x2={p.x} y2={p.y} stroke="currentColor" strokeOpacity=".12"/>})}
    <path d={arcPath([-55,55],190)} fill="none" stroke="currentColor" strokeOpacity=".24" strokeDasharray="3 5"/>
    <text x="360" y="286" textAnchor="middle" fontSize="11" fill="currentColor" opacity=".58">{t.rxReference}</text>
    {mode==='multi'&&<path d={wedgePath([-55,55])} fill="none" stroke="currentColor" strokeOpacity=".22" strokeDasharray="6 5"/>}
    {data?.coverage_supports_deg.map((support,index)=>{const sector=data.sectors[index];if(!sector)return null;const centre=point(sector.centre_across_track_deg,132);const selectedNow=mode==='multi'&&sector.sector_id===selectedSectorId;return <g key={sector.sector_id} role={mode==='multi'?'button':undefined} tabIndex={mode==='multi'?0:undefined} aria-label={`${t.sector} ${sector.sector_id}: ${support[0].toFixed(0)}° to ${support[1].toFixed(0)}°`} onClick={()=>mode==='multi'&&setSelectedSectorId(sector.sector_id)} onKeyDown={e=>{if(mode==='multi'&&(e.key==='Enter'||e.key===' ')){e.preventDefault();setSelectedSectorId(sector.sector_id)}}} style={{cursor:mode==='multi'?'pointer':'default'}}><path d={wedgePath(support)} fill="currentColor" fillOpacity={selectedNow?.16:.08} stroke="currentColor" strokeWidth={selectedNow?3:1.5} strokeOpacity={selectedNow?.8:.42}/><line x1={ORIGIN_X} y1={ORIGIN_Y} x2={centre.x} y2={centre.y} stroke="currentColor" strokeWidth={selectedNow?2:1} strokeOpacity={selectedNow?.75:.32}/><text x={centre.x} y={centre.y} textAnchor="middle" fontSize="12" fontWeight={selectedNow?700:500} fill="currentColor">{sector.sector_id}</text></g>})}
    <circle cx={ORIGIN_X} cy={ORIGIN_Y} r="7" fill="currentColor"/><text x={ORIGIN_X-10} y={ORIGIN_Y-13} textAnchor="end" fontSize="11" fill="currentColor">TX</text>
    <text x="74" y="270" fontSize="11" fill="currentColor" opacity=".7">{t.port} +55°</text><text x="646" y="270" textAnchor="end" fontSize="11" fill="currentColor" opacity=".7">−55° {t.starboard}</text>
   </svg>
   <div className="d10-compare-note"><strong>{t.current}: {mode==='single'?t.single:t.multi}</strong><span>{t.compare}</span></div><div className="d10-readouts">{data?.sectors.map(sector=><div key={sector.sector_id}><small>{sector.sector_id}</small><strong>{sector.frequency_khz.toFixed(0)} kHz</strong><span><Waves size={13}/>{(sector.wavelength_m*1000).toFixed(2)} mm {t.wavelength.toLowerCase()} · {sector.pulse_duration_ms.toFixed(2)} ms</span></div>)}</div></div>
   <div className="d10-panel"><div className="d10-panel-title"><Waves size={18}/><div><small>{t.timing}</small><strong>{t.timingLegend.toUpperCase()}</strong></div></div><div className="d10-timeline">{data?.sectors.map(sector=><div className={`d10-timeline-row ${mode==='multi'&&sector.sector_id===selectedSectorId?'selected':''}`} key={sector.sector_id} onClick={()=>mode==='multi'&&setSelectedSectorId(sector.sector_id)}><span>{sector.sector_id}</span><div><i style={{marginLeft:`${sector.tx_delay_ms/maxDelay*72}%`,width:`${Math.max(sector.pulse_duration_ms/maxDelay*72,4)}%`}}/><small>{sector.tx_delay_ms.toFixed(2)} → {(sector.tx_delay_ms+sector.pulse_duration_ms).toFixed(2)} ms</small></div><strong>{t.group} {groupFor(sector.sector_id)+1}</strong></div>)}</div><div className="d10-groups">{data?.transmit_groups.map((group,index)=><span key={index}><strong>{t.group} {index+1}</strong>{group.join(' + ')}{group.length>1?` · ${t.simultaneous}`:''}</span>)}</div></div></>}</section>
 </main></div>
}