import { AlertTriangle, RotateCcw } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Parameter='delta_lx'|'delta_ly'|'delta_t'|'delta_rho'|'delta_kappa'|'delta_sss';
type Point={along_m:number;across_m:number;depth_m:number;residual_m:number};
type Metadata={symbol:string;unit:string;zero_value:number;default_demo_value:number;sign_semantics:string};
type Result={parameter:Parameter;configured_value:number;parameter_metadata:Metadata;baseline:Point[];changed:Point[];display_scale_m:number;motion_context:Record<string,string|number>;sensor_context:Record<string,string|number>;limitations:string[];reference_role:'neutral_estimator_construct';mode:'visualize_only'};
const parameters:Parameter[]=['delta_lx','delta_ly','delta_t','delta_rho','delta_kappa','delta_sss'];
const fallback:Record<Parameter,{symbol:string;unit:string}>={delta_lx:{symbol:'ΔLx',unit:'m'},delta_ly:{symbol:'ΔLy',unit:'m'},delta_t:{symbol:'Δt',unit:'s'},delta_rho:{symbol:'Δρ',unit:'1'},delta_kappa:{symbol:'Δκ',unit:'rad'},delta_sss:{symbol:'ΔSSS',unit:'m/s'}};

export default function PatchRiscLab(){
 const[lang,setLang]=useState<'en'|'pt'>('en');const[parameter,setParameter]=useState<Parameter>('delta_lx');const[value,setValue]=useState<number|null>(null);const[data,setData]=useState<Result|null>(null);const[error,setError]=useState(false);
 const pt=lang==='pt';
 useEffect(()=>{setValue(null)},[parameter]);
 useEffect(()=>{const ac=new AbortController();setError(false);const body:value===null?{parameter}:{parameter,value};fetch('/api/v1/pedagogical/patch-test/risc-visualization',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:ac.signal}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then((next:Result)=>{setData(next);if(value===null)setValue(next.configured_value)}).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>ac.abort()},[parameter,value]);
 const meta=data?.parameter_metadata;const zero=meta?.zero_value??0;const demo=meta?.default_demo_value??1;const span=Math.max(Math.abs(demo-zero)*2,parameter==='delta_rho'?.08:.01);const min=parameter==='delta_rho'?Math.max(.01,zero-span):zero-span;const max=zero+span;const step=Math.max(span/100,.0001);
 const scale=data?.display_scale_m??2.5;
 const plot=useMemo(()=>{const points=[...(data?.baseline??[]),...(data?.changed??[])];const along=points.map(p=>p.along_m);return{minA:Math.min(...along,0),maxA:Math.max(...along,1)}},[data]);
 const x=(v:number)=>44+(v-plot.minA)/Math.max(plot.maxA-plot.minA,1e-9)*692;const y=(v:number)=>155-v/scale*118;
 const path=(points:Point[],field:'across_m'|'residual_m')=>points.map((p,i)=>`${i?'L':'M'}${x(p.along_m).toFixed(1)},${y(field==='residual_m'?p.residual_m:p.across_m).toFixed(1)}`).join(' ');
 const reset=()=>meta&&setValue(meta.zero_value);
 return <main className="p6-lab"><header><div><span>P6 · {pt?'DIAGNÓSTICO AVANÇADO':'ADVANCED DIAGNOSTICS'}</span><h1>{pt?'Como um erro de integração deforma o campo residual?':'How does an integration error deform the residual field?'}</h1><p>{pt?'Influência de modelo após o Patch Test clássico — não é estimativa nem diagnóstico automático.':'Model influence after the classic Patch Test — not an estimate or automatic diagnosis.'}</p></div><button onClick={()=>setLang(v=>v==='en'?'pt':'en')}>{pt?'EN':'PT-BR'}</button></header>
 <div className="p6-layout"><aside className="p6-controls"><small>{pt?'PARÂMETRO ATIVO':'ACTIVE PARAMETER'}</small><div className="p6-parameters">{parameters.map(p=><button key={p} className={p===parameter?'active':''} onClick={()=>setParameter(p)}><strong>{fallback[p].symbol}</strong><span>{fallback[p].unit}</span></button>)}</div>{meta&&<><label>{pt?'Magnitude candidata':'Candidate magnitude'}<output>{(value??meta.default_demo_value).toFixed(parameter==='delta_sss'?1:parameter==='delta_rho'?3:3)} {meta.unit}</output><input type="range" min={min} max={max} step={step} value={value??meta.default_demo_value} onChange={e=>setValue(+e.target.value)}/></label><div className="p6-sign"><small>{pt?'CONVENÇÃO DE SINAL':'SIGN CONVENTION'}</small><p>{meta.sign_semantics}</p></div><button className="p6-reset" onClick={reset}><RotateCcw/>{pt?'Zerar influência':'Reset influence'}</button></>}</aside>
 <section className="p6-workspace">{error?<div className="p6-error"><AlertTriangle/>{pt?'API indisponível':'API unavailable'}</div>:data&&<><div className="p6-scene"><div className="p6-scene-head"><div><small>{pt?'CAMPO RESIDUAL ESTRUTURADO':'STRUCTURED RESIDUAL FIELD'}</small><strong>{meta?.symbol} = {data.configured_value.toFixed(3)} {meta?.unit}</strong></div><div className="p6-scale">{pt?'escala fixa':'fixed scale'} ±{scale.toFixed(1)} m</div></div><svg viewBox="0 0 780 190" role="img" aria-label={pt?'Referência neutra e resposta alterada':'Neutral reference and changed response'}><line x1="44" y1="155" x2="736" y2="155" className="p6-axis"/><line x1="44" y1="37" x2="736" y2="37" className="p6-bound"/><path d={path(data.baseline,'across_m')} className="p6-baseline"/><path d={path(data.changed,'across_m')} className="p6-changed"/></svg><div className="p6-legend"><span className="neutral">{pt?'Referência neutra':'Neutral reference'}</span><span className="changed">{pt?'Resposta do modelo':'Model response'}</span></div></div>
 <div className="p6-profile"><small>{pt?'MAGNITUDE RESIDUAL AO LONGO DA LINHA':'RESIDUAL MAGNITUDE ALONG LINE'}</small><svg viewBox="0 0 780 190" role="img"><line x1="44" y1="155" x2="736" y2="155" className="p6-axis"/><path d={path(data.changed,'residual_m')} className="p6-residual"/></svg></div>
 <div className="p6-context"><span>{pt?'Movimento':'Motion'}<b>{Number(data.motion_context.roll_amplitude_deg).toFixed(1)}° roll · {Number(data.motion_context.pitch_amplitude_deg).toFixed(1)}° pitch</b></span><span>{pt?'Sensor':'Sensor'}<b>{data.sensor_context.depth_m} m · {data.sensor_context.frame}</b></span></div>
 <section className="p6-warning"><AlertTriangle/><div><strong>{pt?'Modelo potencialmente confundido':'Potentially confounded model'}</strong><p>{pt?'Padrões parecidos podem ter causas físicas diferentes. A referência é uma construção neutra, não Truth.':'Similar patterns may have different physical causes. The reference is a neutral construct, not Truth.'}</p></div></section></>}</section></div></main>
}