import { ChevronRight, RotateCcw } from 'lucide-react';
import { useEffect, useId, useMemo, useState } from 'react';

type Vec={x:number;y:number;z:number;unit:string};
type Response={scenario_id:string;stages:string[];active_stage:string;stage_index:number;ping_index:number;beam_index:number;detection_index:number;detection_method:string;twtt_seconds:number;reconstructed_range_m:number;detected_across_track_angle_rad:number|null;associated_pose_position:Vec;truth_sounding:Vec;reconstructed_sounding:Vec;truth_minus_reconstructed:Vec;reconstruction_basis:string;semantics:Record<string,string>};
type Axis3={x:number;y:number;z:number}; type Attitude={roll:number;pitch:number;yaw:number}; type Lang='en'|'pt';
type Milestone='detection'|'range'|'sensor'|'vessel'|'pose'|'sounding'|'compare';
const defaults={twttMs:40,angleDeg:17.46,position:{x:0,y:0,z:0} as Axis3,attitude:{roll:0,pitch:0,yaw:0} as Attitude,lever:{x:0,y:0,z:0} as Axis3,soundSpeed:1565,pingIndex:12,rxStartMs:10,rxEndMs:100};
const milestoneStage:Record<Milestone,string>={detection:'bottom-detection',range:'twtt-range',sensor:'beam-angle',vessel:'beam-angle',pose:'pose-association',sounding:'reconstruction',compare:'truth-observed'};
const milestones:Milestone[]=['detection','range','sensor','vessel','pose','sounding','compare'];
const initialLanguage=():Lang=>sessionStorage.getItem('hydrosim-language')==='pt'?'pt':'en'; const fmt=(v:number,d=2)=>Number.isFinite(v)?v.toFixed(d):'—';
const text={en:{title:'From detection to sounding',observed:'Observed acoustic detection',detection:'Detection',range:'Range / path',sensor:'Sensor geometry',vessel:'Vessel geometry',pose:'Pose association',sounding:'Sounding',compare:'Compare',twtt:'TWTT',angle:'Detected angle',soundSpeed:'Sound speed',lever:'Sensor lever arm',position:'Vessel position',attitude:'Vessel attitude',truth:'Truth',reconstructed:'Reconstructed sounding',difference:'Truth − reconstructed',reset:'Reset',basis:'Reconstruction basis',method:'Detection method',echo:'Retained echo',sensorAnchor:'Sensor',vesselFrame:'Vessel / VRP',poseAnchor:'Associated pose'},pt:{title:'Da detecção à sondagem',observed:'Detecção acústica observada',detection:'Detecção',range:'Distância / caminho',sensor:'Geometria do sensor',vessel:'Geometria da embarcação',pose:'Associação da pose',sounding:'Sondagem',compare:'Comparar',twtt:'TWTT',angle:'Ângulo detectado',soundSpeed:'Velocidade do som',lever:'Lever arm do sensor',position:'Posição da embarcação',attitude:'Atitude da embarcação',truth:'Referência',reconstructed:'Sondagem reconstruída',difference:'Referência − reconstruída',reset:'Reiniciar',basis:'Base da reconstrução',method:'Método de detecção',echo:'Eco retido',sensorAnchor:'Sensor',vesselFrame:'Embarcação / VRP',poseAnchor:'Pose associada'}};
function AxisInputs({value,onChange}:{value:Axis3;onChange:(v:Axis3)=>void}){return <div className="sf-axis3">{(['x','y','z'] as const).map(k=><label key={k}><span>{k.toUpperCase()}</span><input type="number" step="0.1" value={value[k]} onChange={e=>onChange({...value,[k]:Number(e.target.value)})}/></label>)}</div>}
function AttitudeInputs({value,onChange}:{value:Attitude;onChange:(v:Attitude)=>void}){return <div className="sf-axis3">{(['roll','pitch','yaw'] as const).map(k=><label key={k}><span>{k[0].toUpperCase()}</span><input type="number" step="0.5" value={value[k]} onChange={e=>onChange({...value,[k]:Number(e.target.value)})}/></label>)}</div>}
export default function SoundingFormationLab({onBack:_onBack}:{onBack:()=>void}){
 const[lang,setLang]=useState<Lang>(initialLanguage); const t=text[lang]; const[data,setData]=useState<Response|null>(null); const[milestone,setMilestone]=useState<Milestone>('detection'); const[loading,setLoading]=useState(false); const[error,setError]=useState(false);
 const[twttMs,setTwttMs]=useState(defaults.twttMs); const[angleDeg,setAngleDeg]=useState(defaults.angleDeg); const[position,setPosition]=useState<Axis3>(defaults.position); const[attitude,setAttitude]=useState<Attitude>(defaults.attitude); const[lever,setLever]=useState<Axis3>(defaults.lever); const[soundSpeed,setSoundSpeed]=useState(defaults.soundSpeed); const marker=useId().replace(/:/g,'');
 const stage=milestoneStage[milestone]; const request=useMemo(()=>({active_stage:stage,twtt_seconds:twttMs/1000,detected_across_track_angle_rad:angleDeg*Math.PI/180,position_x_m:position.x,position_y_m:position.y,position_z_m:position.z,roll_deg:attitude.roll,pitch_deg:attitude.pitch,yaw_deg:attitude.yaw,lever_arm_x_m:lever.x,lever_arm_y_m:lever.y,lever_arm_z_m:lever.z,sound_speed_mps:soundSpeed,ping_index:defaults.pingIndex,trigger_time_seconds:0,tx_time_seconds:0,rx_start_time_seconds:defaults.rxStartMs/1000,rx_end_time_seconds:defaults.rxEndMs/1000}),[stage,twttMs,angleDeg,position,attitude,lever,soundSpeed]);
 useEffect(()=>{const sync=(e:Event)=>setLang((e as CustomEvent<Lang>).detail);window.addEventListener('hydrosim-language-change',sync);return()=>window.removeEventListener('hydrosim-language-change',sync)},[]);
 useEffect(()=>{const c=new AbortController();const timer=window.setTimeout(()=>{setLoading(true);setError(false);fetch('/api/v1/pedagogical/sounding-formation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request),signal:c.signal}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(true)}).finally(()=>setLoading(false))},70);return()=>{clearTimeout(timer);c.abort()}},[request]);
 const angle=data?.detected_across_track_angle_rad==null?angleDeg:data.detected_across_track_angle_rad*180/Math.PI; const idx=milestones.indexOf(milestone); const showTruth=milestone==='compare';
 const showRange=idx>=1,showSensor=idx>=2,showVessel=idx>=3,showPose=idx>=4,showSounding=idx>=5; const scale=2.2,ox=540,oy=120; const px=(v:number)=>ox+v*scale,py=(v:number)=>oy+v*scale; const pose=data?.associated_pose_position; const recon=data?.reconstructed_sounding; const truth=data?.truth_sounding;
 // The scene uses API-returned pose/sounding coordinates only. Sensor/vessel marks are presentation anchors, not a frontend frame reconstruction.
 const sensorX=540,sensorY=180;
 const reset=()=>{setMilestone('detection');setTwttMs(defaults.twttMs);setAngleDeg(defaults.angleDeg);setPosition({...defaults.position});setAttitude({...defaults.attitude});setLever({...defaults.lever});setSoundSpeed(defaults.soundSpeed)};
 return <main className="sf-lab sf-reconstruction-lab">
  <header className="sf-observed-strip"><div><small>OBSERVED</small><strong>{t.observed}</strong></div><span>Ping {data?.ping_index??defaults.pingIndex} / Beam {data?.beam_index??'—'} / Detection {data?.detection_index??'—'}</span><span>{t.twtt} {fmt((data?.twtt_seconds??twttMs/1000)*1000,1)} ms</span><span>{t.angle} {fmt(angle,1)}°</span></header>
  <section className="sf-layout">
   <aside className="sf-inputs"><h2>{t.title}</h2><div className="sf-control"><label><span>{t.twtt}</span><strong>{twttMs} ms</strong></label><input type="range" min="15" max="100" value={twttMs} onChange={e=>setTwttMs(Number(e.target.value))}/></div><div className="sf-control"><label><span>{t.angle}</span><strong>{fmt(angleDeg,1)}°</strong></label><input type="range" min="-60" max="60" step="0.5" value={angleDeg} onChange={e=>setAngleDeg(Number(e.target.value))}/></div>
    {(milestone==='range'||milestone==='sensor')&&<div className="sf-control"><label><span>{t.soundSpeed}</span><strong>{soundSpeed} m/s</strong></label><input type="range" min="1450" max="1600" value={soundSpeed} onChange={e=>setSoundSpeed(Number(e.target.value))}/></div>}
    {milestone==='vessel'&&<div className="sf-group"><label>{t.lever} (m)</label><AxisInputs value={lever} onChange={setLever}/></div>}
    {(milestone==='pose'||milestone==='sounding'||milestone==='compare')&&<><div className="sf-group"><label>{t.position} (m)</label><AxisInputs value={position} onChange={setPosition}/></div><div className="sf-group"><label>{t.attitude} (°)</label><AttitudeInputs value={attitude} onChange={setAttitude}/></>}
    <button className="reset" onClick={reset}><RotateCcw size={15}/>{t.reset}</button>
   </aside>
   <div className="sf-maincol"><div className="sf-workspace"><div className="sf-scene"><svg viewBox="0 0 1100 620" className="sounding-transform-scene" role="img" aria-label={`${t.title}: ${t[milestone]}`}><defs><marker id={`${marker}-arrow`} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8Z"/></marker></defs><rect x="0" y="0" width="1100" height="620" className="sf-water"/><line x1="0" y1="520" x2="1100" y2="520" className="sf-bottom"/>
      <g className="sf-detection-mark" data-stage="detection"><path d="M510 500 Q540 468 570 500 Q540 514 510 500Z"/><circle cx="540" cy="492" r="5"/><text x="580" y="497">{t.echo}</text></g>
      {showRange&&<line data-stage="range" x1={sensorX} y1={sensorY} x2="540" y2="492" className="sf-observation-path" markerEnd={`url(#${marker}-arrow)`}/>} 
      {showSensor&&<g className="sf-frame" data-stage="sensor"><circle cx={sensorX} cy={sensorY} r="7"/><line x1={sensorX-34} y1={sensorY} x2={sensorX+34} y2={sensorY}/><text x={sensorX+12} y={sensorY-12}>{t.sensorAnchor}</text></g>}
      {showVessel&&<g className="sf-frame" data-stage="vessel"><rect x="470" y="116" width="140" height="34" rx="16"/><line x1="540" y1="116" x2="540" y2="82" markerEnd={`url(#${marker}-arrow)`}/><line x1="540" y1="133" x2="588" y2="133" markerEnd={`url(#${marker}-arrow)`}/><text x="620" y="139">{t.vesselFrame}</text></g>}
      {showPose&&pose&&<g className="sf-frame" data-stage="pose"><circle cx={px(pose.y)} cy={py(pose.z)} r="9"/><line x1={px(pose.y)} y1={py(pose.z)} x2={px(pose.y)+42} y2={py(pose.z)} markerEnd={`url(#${marker}-arrow)`}/><text x={px(pose.y)+12} y={py(pose.z)-12}>{t.poseAnchor}</text></g>}
      {showSounding&&recon&&<><line data-stage="sounding" x1={sensorX} y1={sensorY} x2={px(recon.y)} y2={py(recon.z)} className="sf-observation-path"/><circle data-stage="sounding" cx={px(recon.y)} cy={py(recon.z)} r="9" className="sf-recon"/><text data-stage="sounding" x={px(recon.y)+12} y={py(recon.z)-10}>{t.reconstructed}</text></>}
      {showTruth&&truth&&recon&&<><circle cx={px(truth.y)} cy={py(truth.z)} r="9" className="sf-truth"/><line x1={px(truth.y)} y1={py(truth.z)} x2={px(recon.y)} y2={py(recon.z)} className="sf-error-vector"/><text x={px(truth.y)+12} y={py(truth.z)+22}>{t.truth}</text></>}</svg></div>
     <aside className="sf-readouts">{showRange&&<div><small>{lang==='en'?'Range':'Distância'}</small><strong>{data?`${fmt(data.reconstructed_range_m)} m`:'—'}</strong></div>}{showSounding&&<div className="wide"><small>{t.reconstructed}</small><strong>{data?`X ${fmt(data.reconstructed_sounding.x)} · Y ${fmt(data.reconstructed_sounding.y)} · Z ${fmt(data.reconstructed_sounding.z)} m`:'—'}</strong></div>}{showTruth&&<><div className="wide"><small>{t.truth}</small><strong>{data?`X ${fmt(data.truth_sounding.x)} · Y ${fmt(data.truth_sounding.y)} · Z ${fmt(data.truth_sounding.z)} m`:'—'}</strong></div><div className="wide accent"><small>{t.difference}</small><strong>{data?`ΔX ${fmt(data.truth_minus_reconstructed.x)} · ΔY ${fmt(data.truth_minus_reconstructed.y)} · ΔZ ${fmt(data.truth_minus_reconstructed.z)} m`:'—'}</strong></div></>}<div className="wide"><small>{t.method}</small><strong>{data?.detection_method??'—'}</strong></div>{showSounding&&<div className="wide"><small>{t.basis}</small><strong>{data?.reconstruction_basis??'—'}</strong></div>}</aside></div>
    <nav className="sf-transform-rail" aria-label={t.title}>{milestones.map((m,i)=><button key={m} className={m===milestone?'active':i<idx?'done':''} onClick={()=>setMilestone(m)}><span>{i+1}</span>{t[m]}{i<milestones.length-1&&<ChevronRight size={14}/>}</button>)}</nav>
   </div>
  </section>{(loading||error)&&<div className={`sf-status ${error?'error':''}`}>{error?(lang==='en'?'Unable to update this view.':'Não foi possível atualizar esta visualização.'):(lang==='en'?'Updating…':'Atualizando…')}</div>}
 </main>
}