import { useEffect, useState } from 'react';
import { ArrowLeft, Clock3, Languages, RotateCcw, Waves } from 'lucide-react';

type Lang='en'|'pt';
type EventKind='trigger'|'tx'|'rx_start'|'rx_end'|'sensor_sample'|'sensor_available';
type StreamId='position'|'attitude';
type TimelineEvent={kind:EventKind;time_s:number;state:string};
type Association={stream_id:StreamId;update_rate_hz:number;sample_period_s:number;latency_ms:number;tx_time_s:number;available:boolean;sample_time_s:number|null;availability_time_s:number|null;age_s:number|null;represented_along_track_m:number|null;along_track_timing_consequence_m:number|null};
type Response={trigger_time_s:number;tx_time_s:number;rx_start_time_s:number;rx_end_time_s:number;receive_duration_ms:number;tx_to_rx_end_ms:number;sensor_sample_time_s:number;sensor_available_time_s:number;sensor_latency_ms:number;vessel_speed_mps:number;associations:Association[];timeline:TimelineEvent[]};
const defaults={tx:1,rxStart:2,rxDuration:20,sample:0,latency:8,positionRate:10,attitudeRate:100,positionLatency:20,attitudeLatency:8,speed:5,position:true,attitude:true};
const TIMELINE_MAX_MS=70;
const copy={
 en:{title:'Timing & Latency',intro:'Change sensor timing and vessel speed, then see which samples are actually applied to each ping.',back:'System Map',lang:'PT-BR',tx:'TX delay',rxStart:'RX start delay',rxDuration:'Receive window',sample:'Stream start time',latency:'Timeline latency',positionRate:'Position update rate',attitudeRate:'Attitude update rate',positionLatency:'Position latency',attitudeLatency:'Attitude latency',speed:'Vessel speed',streams:'Streams used',position:'Position',attitude:'Attitude',reset:'Reset',ping:'Ping events',sensor:'Sensor events',trigger:'Trigger',txEvent:'Transmit',rxOpen:'RX starts',rxClose:'RX ends',sampleEvent:'Sample',available:'Available',window:'Receive window',span:'Trigger → RX end',latencyRead:'Timeline latency',alignment:'Timing alignment',association:'Sample applied at TX',age:'Sample age',sampleTime:'Sample time',availability:'Available at',spatial:'Along-track timing consequence',noPosition:'Position stream not selected',noAttitude:'Attitude stream not selected',unavailable:'No sample is available yet at transmit time',attitudeNote:'Attitude timing is shown as age only; it is not converted to metres.',positionNote:'Signed along-track consequence from the position sample applied at transmit time.',early:'Timeline sample available before RX closes',late:'Timeline sample available after RX closes',error:'Timing data could not be updated. Adjust the controls or restore the baseline.'},
 pt:{title:'Timing & Latência',intro:'Altere o tempo dos sensores e a velocidade da embarcação e veja quais amostras são realmente aplicadas a cada ping.',back:'Mapa do Sistema',lang:'EN',tx:'Atraso de TX',rxStart:'Atraso de início RX',rxDuration:'Janela de recepção',sample:'Início dos fluxos',latency:'Latência da linha do tempo',positionRate:'Taxa de atualização de posição',attitudeRate:'Taxa de atualização de atitude',positionLatency:'Latência de posição',attitudeLatency:'Latência de atitude',speed:'Velocidade da embarcação',streams:'Fluxos usados',position:'Posição',attitude:'Atitude',reset:'Restaurar',ping:'Eventos do ping',sensor:'Eventos do sensor',trigger:'Disparo',txEvent:'Transmissão',rxOpen:'Início RX',rxClose:'Fim RX',sampleEvent:'Amostra',available:'Disponível',window:'Janela de recepção',span:'Disparo → fim RX',latencyRead:'Latência da linha do tempo',alignment:'Alinhamento temporal',association:'Amostra aplicada no TX',age:'Idade da amostra',sampleTime:'Instante da amostra',availability:'Disponível em',spatial:'Consequência temporal ao longo da trajetória',noPosition:'Fluxo de posição não selecionado',noAttitude:'Fluxo de atitude não selecionado',unavailable:'Ainda não há amostra disponível no instante da transmissão',attitudeNote:'O tempo da atitude é mostrado apenas como idade; não é convertido para metros.',positionNote:'Consequência longitudinal com sinal, calculada para a amostra de posição aplicada no instante da transmissão.',early:'Amostra da linha do tempo disponível antes do fim da recepção',late:'Amostra da linha do tempo disponível após o fim da recepção',error:'Não foi possível atualizar os dados de tempo. Ajuste os controles ou restaure a configuração inicial.'}
};
const eventLabel=(kind:EventKind,t:typeof copy.en)=>({trigger:t.trigger,tx:t.txEvent,rx_start:t.rxOpen,rx_end:t.rxClose,sensor_sample:t.sampleEvent,sensor_available:t.available}[kind]);
export default function TimingLab({onBack}:{onBack:()=>void}){
 const[lang,setLang]=useState<Lang>('en');const[tx,setTx]=useState(defaults.tx);const[rxStart,setRxStart]=useState(defaults.rxStart);const[rxDuration,setRxDuration]=useState(defaults.rxDuration);const[sample,setSample]=useState(defaults.sample);const[latency,setLatency]=useState(defaults.latency);const[positionRate,setPositionRate]=useState(defaults.positionRate);const[attitudeRate,setAttitudeRate]=useState(defaults.attitudeRate);const[positionLatency,setPositionLatency]=useState(defaults.positionLatency);const[attitudeLatency,setAttitudeLatency]=useState(defaults.attitudeLatency);const[speed,setSpeed]=useState(defaults.speed);const[positionOn,setPositionOn]=useState(defaults.position);const[attitudeOn,setAttitudeOn]=useState(defaults.attitude);const[data,setData]=useState<Response|null>(null);const[error,setError]=useState(false);const t=copy[lang];
 useEffect(()=>{const ac=new AbortController();setError(false);const selected_streams:StreamId[]=[];if(positionOn)selected_streams.push('position');if(attitudeOn)selected_streams.push('attitude');fetch('/api/v1/pedagogical/timing',{method:'POST',headers:{'Content-Type':'application/json'},signal:ac.signal,body:JSON.stringify({trigger_time_s:0,tx_delay_ms:tx,rx_start_delay_ms:rxStart,rx_duration_ms:rxDuration,sensor_sample_time_s:sample/1000,sensor_latency_ms:latency,selected_streams,position_update_rate_hz:positionRate,attitude_update_rate_hz:attitudeRate,position_latency_ms:positionLatency,attitude_latency_ms:attitudeLatency,vessel_speed_mps:speed})}).then(async r=>{if(!r.ok)throw new Error('timing update rejected');return r.json() as Promise<Response>}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>ac.abort()},[tx,rxStart,rxDuration,sample,latency,positionRate,attitudeRate,positionLatency,attitudeLatency,speed,positionOn,attitudeOn]);
 const maxMs=TIMELINE_MAX_MS;const x=(seconds:number)=>4+92*(seconds*1000/maxMs);const pingEvents=(data?.timeline??[]).filter(e=>['trigger','tx','rx_start','rx_end'].includes(e.kind));const sensorEvents=(data?.timeline??[]).filter(e=>['sensor_sample','sensor_available'].includes(e.kind));const availableBefore=(data?.sensor_available_time_s??0)<=(data?.rx_end_time_s??0);const position=data?.associations.find(a=>a.stream_id==='position');const attitude=data?.associations.find(a=>a.stream_id==='attitude');
 const slider=(label:string,value:number,setter:(n:number)=>void,min:number,max:number,step:number,unit='ms')=><label>{label}<strong>{value.toFixed(step<1?1:0)} {unit}</strong><input type="range" min={min} max={max} step={step} value={value} onChange={e=>setter(+e.target.value)}/></label>;
 const associationCard=(stream:StreamId,a:Association|undefined,selected:boolean)=><article><small>{stream==='position'?t.position:t.attitude}</small>{!selected?<strong>{stream==='position'?t.noPosition:t.noAttitude}</strong>:!a?.available?<strong>{t.unavailable}</strong>:<><strong>{t.association}</strong><span>{t.sampleTime}: {(a.sample_time_s!*1000).toFixed(1)} ms</span><span>{t.availability}: {(a.availability_time_s!*1000).toFixed(1)} ms</span><span>{t.age}: {(a.age_s!*1000).toFixed(1)} ms</span>{stream==='position'&&<><span>{t.spatial}: <b>{a.along_track_timing_consequence_m?.toFixed(2)??'—'} m</b></span><span>{t.positionNote}</span></>}{stream==='attitude'&&<span>{t.attitudeNote}</span>}</>}</article>;
 const reset=()=>{setTx(defaults.tx);setRxStart(defaults.rxStart);setRxDuration(defaults.rxDuration);setSample(defaults.sample);setLatency(defaults.latency);setPositionRate(defaults.positionRate);setAttitudeRate(defaults.attitudeRate);setPositionLatency(defaults.positionLatency);setAttitudeLatency(defaults.attitudeLatency);setSpeed(defaults.speed);setPositionOn(defaults.position);setAttitudeOn(defaults.attitude)};
 return <div className="d14-lab"><header><button onClick={onBack}><ArrowLeft size={16}/>{t.back}</button><div><span>PED-D14 · TIMING & LATENCY</span><h1>{t.title}</h1><p>{t.intro}</p></div><button onClick={()=>setLang(lang==='en'?'pt':'en')}><Languages size={16}/>{t.lang}</button></header><main><aside>{slider(t.tx,tx,setTx,0,12,.5)}{slider(t.rxStart,rxStart,setRxStart,0,15,.5)}{slider(t.rxDuration,rxDuration,setRxDuration,4,35,1)}{slider(t.sample,sample,setSample,0,20,.5)}{slider(t.latency,latency,setLatency,0,30,.5)}{slider(t.positionRate,positionRate,setPositionRate,1,20,1,'Hz')}{slider(t.attitudeRate,attitudeRate,setAttitudeRate,10,200,10,'Hz')}{slider(t.positionLatency,positionLatency,setPositionLatency,0,100,5)}{slider(t.attitudeLatency,attitudeLatency,setAttitudeLatency,0,50,2)}{slider(t.speed,speed,setSpeed,0,12,.5,'m/s')}<fieldset><legend>{t.streams}</legend><label><input type="checkbox" checked={positionOn} onChange={e=>setPositionOn(e.target.checked)}/>{t.position}</label><label><input type="checkbox" checked={attitudeOn} onChange={e=>setAttitudeOn(e.target.checked)}/>{t.attitude}</label></fieldset><button className="d14-reset" onClick={reset}><RotateCcw size={15}/>{t.reset}</button></aside><section className="d14-stage">{error?<div className="d14-error" role="status">{t.error}</div>:<><article className="d14-timeline"><div className="d14-title"><Clock3 size={18}/><strong>{t.alignment}</strong><span>0–{maxMs.toFixed(0)} ms</span></div><div className="d14-axis"><i>0</i><i>{(maxMs/2).toFixed(0)}</i><i>{maxMs.toFixed(0)} ms</i></div><div className="d14-lane"><b>{t.ping}</b><div className="d14-track">{pingEvents.map(e=><span key={e.kind} className={`event ${e.kind}`} style={{left:`${x(e.time_s)}%`}}><i/><em>{eventLabel(e.kind,t)}</em><small>{(e.time_s*1000).toFixed(1)} ms</small></span>)}</div></div><div className="d14-lane"><b>{t.sensor}</b><div className="d14-track sensor">{sensorEvents.map(e=><span key={e.kind} className={`event ${e.kind}`} style={{left:`${x(e.time_s)}%`}}><i/><em>{eventLabel(e.kind,t)}</em><small>{(e.time_s*1000).toFixed(1)} ms</small></span>)}</div></div></article><div className="d14-readouts"><article><Waves size={17}/><small>{t.window}</small><strong>{data?.receive_duration_ms.toFixed(1)??'—'} ms</strong></article><article><Clock3 size={17}/><small>{t.span}</small><strong>{data?.tx_to_rx_end_ms.toFixed(1)??'—'} ms</strong></article><article><Clock3 size={17}/><small>{t.speed}</small><strong>{data?.vessel_speed_mps.toFixed(1)??'—'} m/s</strong></article></div><div className="d14-readouts">{associationCard('position',position,positionOn)}{associationCard('attitude',attitude,attitudeOn)}</div><div className={`d14-consequence ${availableBefore?'early':'late'}`}><strong>{availableBefore?t.early:t.late}</strong></div></>}</section></main></div>}
