import { useEffect, useState } from 'react';
import { ArrowLeft, Clock3, Languages, RotateCcw, Waves } from 'lucide-react';

type Lang='en'|'pt';
type EventKind='trigger'|'tx'|'rx_start'|'rx_end'|'sensor_sample'|'sensor_available';
type TimelineEvent={kind:EventKind;time_s:number;state:string};
type Response={trigger_time_s:number;tx_time_s:number;rx_start_time_s:number;rx_end_time_s:number;receive_duration_ms:number;tx_to_rx_end_ms:number;sensor_sample_time_s:number;sensor_available_time_s:number;sensor_latency_ms:number;timeline:TimelineEvent[]};
const defaults={tx:1,rxStart:2,rxDuration:20,sample:6,latency:8};
const TIMELINE_MAX_MS=70;
const copy={
 en:{title:'Timing & Latency',intro:'Move the ping and sensor timing controls and watch how their events align on the same clock.',back:'System Map',lang:'PT-BR',tx:'TX delay',rxStart:'RX start delay',rxDuration:'Receive window',sample:'Sensor sample time',latency:'Sensor latency',reset:'Reset',ping:'Ping events',sensor:'Sensor events',trigger:'Trigger',txEvent:'Transmit',rxOpen:'RX starts',rxClose:'RX ends',sampleEvent:'Sample',available:'Available',window:'Receive window',span:'Trigger → RX end',latencyRead:'Sensor latency',alignment:'Timing alignment',early:'Sensor data available before RX closes',late:'Sensor data available after RX closes',limit:'This lesson shows timing alignment. A resulting spatial sounding error is not shown yet.',error:'Timing data could not be updated. Adjust the controls or restore the baseline.'},
 pt:{title:'Timing & Latência',intro:'Ajuste os tempos do ping e do sensor e observe como os eventos se alinham no mesmo relógio.',back:'Mapa do Sistema',lang:'EN',tx:'Atraso de TX',rxStart:'Atraso de início RX',rxDuration:'Janela de recepção',sample:'Instante da amostra do sensor',latency:'Latência do sensor',reset:'Restaurar',ping:'Eventos do ping',sensor:'Eventos do sensor',trigger:'Disparo',txEvent:'Transmissão',rxOpen:'Início RX',rxClose:'Fim RX',sampleEvent:'Amostra',available:'Disponível',window:'Janela de recepção',span:'Disparo → fim RX',latencyRead:'Latência do sensor',alignment:'Alinhamento temporal',early:'Dado do sensor disponível antes do fim da recepção',late:'Dado do sensor disponível após o fim da recepção',limit:'Esta lição mostra o alinhamento temporal. O erro espacial resultante na sondagem ainda não é apresentado.',error:'Não foi possível atualizar os dados de tempo. Ajuste os controles ou restaure a configuração inicial.'}
};
const eventLabel=(kind:EventKind,t:typeof copy.en)=>({trigger:t.trigger,tx:t.txEvent,rx_start:t.rxOpen,rx_end:t.rxClose,sensor_sample:t.sampleEvent,sensor_available:t.available}[kind]);
export default function TimingLab({onBack}:{onBack:()=>void}){
 const[lang,setLang]=useState<Lang>('en');const[tx,setTx]=useState(defaults.tx);const[rxStart,setRxStart]=useState(defaults.rxStart);const[rxDuration,setRxDuration]=useState(defaults.rxDuration);const[sample,setSample]=useState(defaults.sample);const[latency,setLatency]=useState(defaults.latency);const[data,setData]=useState<Response|null>(null);const[error,setError]=useState(false);const t=copy[lang];
 useEffect(()=>{const ac=new AbortController();setError(false);fetch('/api/v1/pedagogical/timing',{method:'POST',headers:{'Content-Type':'application/json'},signal:ac.signal,body:JSON.stringify({trigger_time_s:0,tx_delay_ms:tx,rx_start_delay_ms:rxStart,rx_duration_ms:rxDuration,sensor_sample_time_s:sample/1000,sensor_latency_ms:latency})}).then(async r=>{if(!r.ok)throw new Error('timing update rejected');return r.json() as Promise<Response>}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>ac.abort()},[tx,rxStart,rxDuration,sample,latency]);
 const maxMs=TIMELINE_MAX_MS;const x=(seconds:number)=>4+92*(seconds*1000/maxMs);const pingEvents=(data?.timeline??[]).filter(e=>['trigger','tx','rx_start','rx_end'].includes(e.kind));const sensorEvents=(data?.timeline??[]).filter(e=>['sensor_sample','sensor_available'].includes(e.kind));const availableBefore=(data?.sensor_available_time_s??0)<=(data?.rx_end_time_s??0);
 const slider=(label:string,value:number,setter:(n:number)=>void,min:number,max:number,step:number)=><label>{label}<strong>{value.toFixed(step<1?1:0)} ms</strong><input type="range" min={min} max={max} step={step} value={value} onChange={e=>setter(+e.target.value)}/></label>;
 return <div className="d14-lab"><header><button onClick={onBack}><ArrowLeft size={16}/>{t.back}</button><div><span>PED-D14 · TIMING & LATENCY</span><h1>{t.title}</h1><p>{t.intro}</p></div><button onClick={()=>setLang(lang==='en'?'pt':'en')}><Languages size={16}/>{t.lang}</button></header><main><aside>{slider(t.tx,tx,setTx,0,12,.5)}{slider(t.rxStart,rxStart,setRxStart,0,15,.5)}{slider(t.rxDuration,rxDuration,setRxDuration,4,35,1)}{slider(t.sample,sample,setSample,0,35,.5)}{slider(t.latency,latency,setLatency,0,30,.5)}<button className="d14-reset" onClick={()=>{setTx(defaults.tx);setRxStart(defaults.rxStart);setRxDuration(defaults.rxDuration);setSample(defaults.sample);setLatency(defaults.latency)}}><RotateCcw size={15}/>{t.reset}</button></aside><section className="d14-stage">{error?<div className="d14-error">{t.error}</div>:<><article className="d14-timeline"><div className="d14-title"><Clock3 size={18}/><strong>{t.alignment}</strong><span>0–{maxMs.toFixed(0)} ms</span></div><div className="d14-axis"><i>0</i><i>{(maxMs/2).toFixed(0)}</i><i>{maxMs.toFixed(0)} ms</i></div><div className="d14-lane"><b>{t.ping}</b><div className="d14-track">{pingEvents.map(e=><span key={e.kind} className={`event ${e.kind}`} style={{left:`${x(e.time_s)}%`}}><i/><em>{eventLabel(e.kind,t)}</em><small>{(e.time_s*1000).toFixed(1)} ms</small></span>)}</div></div><div className="d14-lane"><b>{t.sensor}</b><div className="d14-track sensor">{sensorEvents.map(e=><span key={e.kind} className={`event ${e.kind}`} style={{left:`${x(e.time_s)}%`}}><i/><em>{eventLabel(e.kind,t)}</em><small>{(e.time_s*1000).toFixed(1)} ms</small></span>)}</div></div></article><div className="d14-readouts"><article><Waves size={17}/><small>{t.window}</small><strong>{data?.receive_duration_ms.toFixed(1)??'—'} ms</strong></article><article><Clock3 size={17}/><small>{t.span}</small><strong>{data?.tx_to_rx_end_ms.toFixed(1)??'—'} ms</strong></article><article><Clock3 size={17}/><small>{t.latencyRead}</small><strong>{data?.sensor_latency_ms.toFixed(1)??'—'} ms</strong></article></div><div className={`d14-consequence ${availableBefore?'early':'late'}`}><strong>{availableBefore?t.early:t.late}</strong><span>{t.limit}</span></div></>}</section></main></div>}
