import { useEffect, useMemo, useState } from 'react';
import { Rotate3D, RotateCcw, Ship } from 'lucide-react';

type Lang='en'|'pt';
type Dof='roll'|'pitch'|'yaw'|'heave';
type V={north_m:number;east_m:number;down_m:number};
type Snapshot={roll_deg:number;pitch_deg:number;yaw_deviation_deg:number;heave_m:number;vrp_position_n_m:V;transducer_position_n_m:V;body_forward_axis_n:V;body_starboard_axis_n:V;body_down_axis_n:V;beam_direction_n:V};
type Response={instantaneous_snapshot?:Snapshot|null};
const initialLanguage=():Lang=>sessionStorage.getItem('hydrosim-language')==='pt'?'pt':'en';
const copy={
 en:{title:'Move one degree of freedom. Follow the rigid body to the beam.',dof:'Isolate motion',roll:'Roll',pitch:'Pitch',yaw:'Yaw',heave:'Heave',angle:'Instantaneous value',reset:'Zero motion',scene:'Rigid-body snapshot',vrp:'VRP',sonar:'Sonar',beam:'Beam direction',forward:'Forward axis',starboard:'Starboard axis',down:'Down axis',cause:'Configured motion',body:'Rigid-body consequence',bottom:'What reaches the bottom',loading:'Updating geometry…',error:'The motion geometry could not be evaluated.',authority:'Geometry from Scientific Core/API',positive:'Heave is positive Up.'},
 pt:{title:'Mova um grau de liberdade. Acompanhe o corpo rígido até o feixe.',dof:'Isole o movimento',roll:'Roll',pitch:'Pitch',yaw:'Yaw',heave:'Heave',angle:'Valor instantâneo',reset:'Zerar movimento',scene:'Instantâneo do corpo rígido',vrp:'VRP',sonar:'Sonar',beam:'Direção do feixe',forward:'Eixo de proa',starboard:'Eixo de boreste',down:'Eixo para baixo',cause:'Movimento configurado',body:'Consequência no corpo rígido',bottom:'O que chega ao fundo',loading:'Atualizando geometria…',error:'Não foi possível avaliar a geometria do movimento.',authority:'Geometria fornecida pelo Core/API',positive:'Heave é positivo para cima.'}
};
const fmt=(v:V)=>`N ${v.north_m.toFixed(2)} · E ${v.east_m.toFixed(2)} · D ${v.down_m.toFixed(2)}`;
export default function VesselMotionLab({onBack:_onBack}:{onBack:()=>void}){
 const[lang,setLang]=useState<Lang>(initialLanguage);const[dof,setDof]=useState<Dof>('roll');const[value,setValue]=useState(10);const[data,setData]=useState<Response|null>(null);const[error,setError]=useState(false);const t=copy[lang];
 useEffect(()=>{const sync=(e:Event)=>setLang((e as CustomEvent<Lang>).detail);window.addEventListener('hydrosim-language-change',sync);return()=>window.removeEventListener('hydrosim-language-change',sync)},[]);
 const configured=useMemo(()=>({roll:dof==='roll'?value:0,pitch:dof==='pitch'?value:0,yaw:dof==='yaw'?value:0,heave:dof==='heave'?value:0}),[dof,value]);
 useEffect(()=>{const ac=new AbortController();setError(false);fetch('/api/v1/pedagogical/vessel-motion',{method:'POST',headers:{'Content-Type':'application/json'},signal:ac.signal,body:JSON.stringify({heading_deg:20,speed_mps:0,start_north_m:0,start_east_m:0,start_down_m:0,duration_seconds:4,sample_count:21,roll:{amplitude_deg:0,period_seconds:6,phase_deg:0},pitch:{amplitude_deg:0,period_seconds:8,phase_deg:0},yaw_deviation:{amplitude_deg:0,period_seconds:10,phase_deg:0},heave:{amplitude_m:0,period_seconds:7,phase_deg:0},instantaneous_snapshot:{roll_deg:configured.roll,pitch_deg:configured.pitch,yaw_deviation_deg:configured.yaw,heave_m:configured.heave,vrp_position_n_m:[0,0,0],heading_deg:20,lever_arm_vrp_to_transducer_b_m:[2,0,3],beam_direction_b:[0,0,1]}})}).then(async r=>{if(!r.ok)throw new Error();return r.json() as Promise<Response>}).then(setData).catch(e=>{if(e.name!=='AbortError'){setData(null);setError(true)}});return()=>ac.abort()},[configured]);
 const s=data?.instantaneous_snapshot??null;const limit=dof==='heave'?3:20;const unit=dof==='heave'?'m':'°';
 const p=(v:V)=>({x:360+v.east_m*22,y:210+v.down_m*18-v.north_m*5});
 const vrp=s?p(s.vrp_position_n_m):null,tx=s?p(s.transducer_position_n_m):null;
 const axisEnd=(origin:{x:number;y:number},v:V,scale=62)=>({x:origin.x+v.east_m*scale,y:origin.y+v.down_m*scale-v.north_m*scale*.35});
 const beamEnd=tx&&s?axisEnd(tx,s.beam_direction_n,150):null;
 return <div className="d12-lab"><main><aside><h2>{t.dof}</h2><div className="d11-targets" role="tablist">{(['roll','pitch','yaw','heave'] as Dof[]).map(k=><button key={k} role="tab" aria-selected={dof===k} className={dof===k?'active':''} onClick={()=>{setDof(k);setValue(k==='heave'?1:10)}}>{t[k]}</button>)}</div><label>{t.angle}<strong>{value.toFixed(1)} {unit}</strong><input aria-label={t.angle} type="range" min={-limit} max={limit} step={dof==='heave'?0.1:1} value={value} onChange={e=>setValue(+e.target.value)}/></label><button type="button" onClick={()=>setValue(0)}><RotateCcw size={16}/>{t.reset}</button>{dof==='heave'&&<small>{t.positive}</small>}</aside><section className="d12-stage"><header className="d12-title"><Ship size={18}/><div><small>{t.scene}</small><strong>{t.title}</strong></div></header>{error?<div className="d12-error" role="status">{t.error}</div>:!s?<div className="d12-error">{t.loading}</div>:<><article className="d12-consequences"><svg viewBox="0 0 720 420" role="img" aria-label={t.scene} style={{width:'100%',minHeight:360}}><line x1="40" y1="350" x2="680" y2="350" stroke="currentColor" strokeOpacity=".18"/><text x="52" y="375">BOTTOM</text>{vrp&&tx&&<><line x1={vrp.x} y1={vrp.y} x2={tx.x} y2={tx.y} stroke="currentColor" strokeWidth="3" strokeOpacity=".35"/><circle cx={vrp.x} cy={vrp.y} r="8"/><text x={vrp.x+12} y={vrp.y-8}>{t.vrp}</text><circle cx={tx.x} cy={tx.y} r="9"/><text x={tx.x+12} y={tx.y-8}>{t.sonar}</text></>}{vrp&&<>{[['forward',s.body_forward_axis_n],['starboard',s.body_starboard_axis_n],['down',s.body_down_axis_n]].map(([name,v])=>{const e=axisEnd(vrp,v as V);return <g key={name as string}><line x1={vrp.x} y1={vrp.y} x2={e.x} y2={e.y} stroke="currentColor" strokeWidth="2"/><text x={e.x+5} y={e.y}>{t[name as 'forward'|'starboard'|'down']}</text></g>})}</>}{tx&&beamEnd&&<><line x1={tx.x} y1={tx.y} x2={beamEnd.x} y2={beamEnd.y} stroke="currentColor" strokeWidth="5" strokeDasharray="8 6"/><text x={beamEnd.x+8} y={beamEnd.y}>{t.beam}</text></>}</svg><div className="d12-read"><span>{t.cause}<strong>{dof.toUpperCase()} {value.toFixed(1)} {unit}</strong></span><span>{t.body}<strong>{t.vrp} {fmt(s.vrp_position_n_m)}</strong><small>{t.sonar} {fmt(s.transducer_position_n_m)}</small></span><span>{t.bottom}<strong>{t.beam} {fmt(s.beam_direction_n)}</strong></span></div></article><div className="causal-strip"><div><small>1</small><strong>{t.cause}</strong><span>{dof.toUpperCase()}</span></div><div><small>2</small><strong>{t.body}</strong><span>{t.vrp} → {t.sonar}</span></div><div><small>3</small><strong>{t.bottom}</strong><span>{t.beam}</span></div></div><p><small>{t.authority}</small></p></>}</section></main></div>
}