import { Anchor, Cpu, Radio, RotateCcw, Satellite, Ship, SlidersHorizontal } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Lang='en'|'pt';
type Vec={x:number;y:number;z:number};
type VesselResponse={vrp_position_m:Vec;gnss_position_m:Vec;imu_position_m:Vec;transducer_position_m:Vec;waterline_z_from_vrp_m:number;static_draft_m:number;keel_z_from_vrp_m:number;transducer_z_from_vrp_m:number;transducer_depth_below_waterline_m:number;water_level_m_relative_to_datum:number;metadata:Record<string,string>};
const api='/api/v1/pedagogical/vessel';
const text={en:{back:'← System map',title:'Vessel reference geometry',lead:'Move the configured installation and read every sensor against one common vessel reference.',controls:'Configured geometry',tx:'Transducer lever arm',gnss:'GNSS lever arm',imu:'IMU lever arm',waterline:'Waterline Z from VRP',draft:'Static draft',level:'Water level relative to datum',reset:'Reset',derived:'Derived geometry',depth:'Transducer depth below waterline',keel:'Keel Z from VRP',frame:'Body frame',loading:'Updating canonical geometry…',error:'Canonical vessel geometry is unavailable.',retry:'Retry',note:'Configured inputs → canonical Python geometry → Derived positions',datum:'Hydrographic datum',wl:'Waterline',vrp:'VRP / origin',keelLabel:'Keel',transducer:'Transducer'},pt:{back:'← Mapa do sistema',title:'Geometria de referência da embarcação',lead:'Altere a instalação configurada e leia cada sensor em relação a uma referência comum da embarcação.',controls:'Geometria configurada',tx:'Lever arm do transdutor',gnss:'Lever arm do GNSS',imu:'Lever arm da IMU',waterline:'Z da linha d’água a partir do VRP',draft:'Calado estático',level:'Nível d’água relativo ao datum',reset:'Restaurar',derived:'Geometria derivada',depth:'Profundidade do transdutor abaixo da linha d’água',keel:'Z da quilha a partir do VRP',frame:'Referencial do corpo',loading:'Atualizando geometria canônica…',error:'A geometria canônica da embarcação está indisponível.',retry:'Tentar novamente',note:'Entradas configuradas → geometria Python canônica → posições derivadas',datum:'Datum hidrográfico',wl:'Linha d’água',vrp:'VRP / origem',keelLabel:'Quilha',transducer:'Transdutor'}};
const defaults={tx:{x:1.2,y:0.0,z:2.1},gnss:{x:-2.5,y:0.4,z:-4.2},imu:{x:0.3,y:0.0,z:-0.8},waterline:-1.1,draft:3.8,level:1.4};
function Axis({label,value,onChange}:{label:string;value:Vec;onChange:(v:Vec)=>void}){return <fieldset className="axis-control"><legend>{label}</legend>{(['x','y','z'] as const).map(k=><label key={k}>{k.toUpperCase()} <output>{value[k].toFixed(1)} m</output><input type="range" min="-6" max="6" step="0.1" value={value[k]} onChange={e=>onChange({...value,[k]:+e.target.value})}/></label>)}</fieldset>}
export default function VesselLab({onBack}:{onBack:()=>void;focus?:string}){
 const[lang,setLang]=useState<Lang>('en');const t=text[lang];const[tx,setTx]=useState(defaults.tx);const[gnss,setGnss]=useState(defaults.gnss);const[imu,setImu]=useState(defaults.imu);const[waterline,setWaterline]=useState(defaults.waterline);const[draft,setDraft]=useState(defaults.draft);const[level,setLevel]=useState(defaults.level);const[data,setData]=useState<VesselResponse|null>(null);const[error,setError]=useState(false);const[nonce,setNonce]=useState(0);
 const body=useMemo(()=>({transducer_lever_arm_m:tx,gnss_lever_arm_m:gnss,imu_lever_arm_m:imu,waterline_z_from_vrp_m:waterline,static_draft_m:draft,water_level_m_relative_to_datum:level}),[tx,gnss,imu,waterline,draft,level]);
 useEffect(()=>{const controller=new AbortController();setError(false);fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>controller.abort()},[body,nonce]);
 const reset=()=>{setTx(defaults.tx);setGnss(defaults.gnss);setImu(defaults.imu);setWaterline(defaults.waterline);setDraft(defaults.draft);setLevel(defaults.level)};
 const zMin=-6,zMax=7,toY=(z:number)=>12+((z-zMin)/(zMax-zMin))*76;
 return <div className="phenomenon-lab vessel-lab"><div className="lab-toolbar"><button className="back-button" onClick={onBack}>{t.back}</button><div className="lab-breadcrumb"><Ship size={17}/><span>PED-D11</span><b>/</b><strong>{t.title}</strong></div><div className="lab-toolbar-actions"><button onClick={()=>setLang(lang==='en'?'pt':'en')}>{lang==='en'?'PT-BR':'EN'}</button></div></div>
 <div className="lab-question"><span>11 · VESSEL & SENSOR REFERENCES</span><h1>{t.title}</h1><p>{t.lead}</p></div>
 <div className="phenomenon-layout"><aside className="control-surface"><div className="control-title"><SlidersHorizontal size={17}/><strong>{t.controls}</strong></div><Axis label={t.tx} value={tx} onChange={setTx}/><Axis label={t.gnss} value={gnss} onChange={setGnss}/><Axis label={t.imu} value={imu} onChange={setImu}/>{[[t.waterline,waterline,setWaterline,-4,3],[t.draft,draft,setDraft,.5,7],[t.level,level,setLevel,-3,5]].map(([label,value,setter,min,max])=><label key={label as string}>{label as string}<output>{(value as number).toFixed(1)} m</output><input type="range" min={min as number} max={max as number} step="0.1" value={value as number} onChange={e=>(setter as (v:number)=>void)(+e.target.value)}/></label>)}<button className="reset" onClick={reset}><RotateCcw size={15}/>{t.reset}</button></aside>
 <section className="phenomenon-stage vessel-stage"><div className="stage-kicker"><div><small>CONFIGURED → DERIVED</small><strong>{t.note}</strong></div></div>{error?<div className="lab-error"><strong>{t.error}</strong><button onClick={()=>setNonce(n=>n+1)}>{t.retry}</button></div>:!data?<div className="lab-loading">{t.loading}</div>:<><div className="vessel-scene" style={{position:'relative',minHeight:430}}><div className="vertical-stack">{[[t.datum,-level],[t.wl,data.waterline_z_from_vrp_m],[t.vrp,0],[t.keelLabel,data.keel_z_from_vrp_m],[t.transducer,data.transducer_z_from_vrp_m]].map(([label,z])=><div key={label as string} className="datum-line" style={{top:`${toY(z as number)}%`}}><span>{label as string} · {(z as number).toFixed(2)} m</span></div>)}</div><div className="geometry-callout"><small>{t.derived}</small><strong>{t.depth}: {data.transducer_depth_below_waterline_m.toFixed(2)} m</strong><span>{t.keel}: {data.keel_z_from_vrp_m.toFixed(2)} m</span></div><div className="sensor-key"><span><Satellite size={15}/> GNSS ({data.gnss_position_m.x.toFixed(1)}, {data.gnss_position_m.y.toFixed(1)}, {data.gnss_position_m.z.toFixed(1)}) m</span><span><Cpu size={15}/> IMU ({data.imu_position_m.x.toFixed(1)}, {data.imu_position_m.y.toFixed(1)}, {data.imu_position_m.z.toFixed(1)}) m</span><span><Radio size={15}/> TX/RX ({data.transducer_position_m.x.toFixed(1)}, {data.transducer_position_m.y.toFixed(1)}, {data.transducer_position_m.z.toFixed(1)}) m</span><span><Anchor size={15}/> {t.frame}: {data.metadata.frame}</span></div></div><div className="causal-strip"><div><small>INPUT</small><strong>Lever arms + references</strong></div><div><small>PYTHON</small><strong>Canonical vessel snapshot</strong></div><div><small>OUTPUT</small><strong>{t.derived}</strong></div></div></>}</section></div></div>
}
