import { Activity, RotateCcw } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Locale='en'|'pt-BR';
type TraceSeries={x:number[];y:number[];x_unit:string;y_unit:string};
type WaveResponse={period_seconds:number;wavelength_m:number;temporal_waveform:TraceSeries;spatial_waveform:TraceSeries;range_offset_m:number|null;metadata:Record<string,number|string>};

const API_BASE=(import.meta.env.VITE_HYDROSIM_API_BASE as string|undefined)??'http://127.0.0.1:8000';
const TIME_WINDOW_MS=0.014;
const copy={
 en:{back:'← System map',kicker:'PED-D1 · ACOUSTIC WAVE & FREQUENCY',title:'Change the wave and see the effect immediately.',frequency:'Frequency',soundSpeed:'Sound speed',phase:'Initial phase',amplitude:'Normalized amplitude',time:'Wave in time',period:'Period',wavelength:'Wavelength',configured:'CONFIGURED',derived:'DERIVED',retry:'Retry',unavailable:'Scientific API unavailable',reset:'Reset',updating:'Updating…',timeAxis:'Time (ms)',amplitudeAxis:'Normalized amplitude'},
 'pt-BR':{back:'← Mapa do sistema',kicker:'PED-D1 · ONDA ACÚSTICA E FREQUÊNCIA',title:'Altere a onda e veja o efeito imediatamente.',frequency:'Frequência',soundSpeed:'Velocidade do som',phase:'Fase inicial',amplitude:'Amplitude normalizada',time:'Onda no tempo',period:'Período',wavelength:'Comprimento de onda',configured:'CONFIGURADO',derived:'DERIVADO',retry:'Tentar novamente',unavailable:'API científica indisponível',reset:'Redefinir',updating:'Atualizando…',timeAxis:'Tempo (ms)',amplitudeAxis:'Amplitude normalizada'}
} as const;

function tracePath(series:TraceSeries|undefined,width=760,height=190){
 if(!series||series.x.length<2||series.x.length!==series.y.length)return'';
 const minX=0,maxX=TIME_WINDOW_MS,minY=-1.05,maxY=1.05,dx=maxX-minX,dy=maxY-minY;
 return series.x.map((x,i)=>`${i?'L':'M'} ${(((x-minX)/dx)*width).toFixed(2)} ${(height-((series.y[i]-minY)/dy)*height).toFixed(2)}`).join(' ')
}
function Trace({series,label,timeAxis,amplitudeAxis}:{series?:TraceSeries;label:string;timeAxis:string;amplitudeAxis:string}){
 const d=useMemo(()=>tracePath(series),[series]);
 return <div className="wave-trace"><div><strong>{label}</strong></div><div className="wave-chart-frame"><span className="wave-y-label">{amplitudeAxis}</span><svg viewBox="0 0 760 220" preserveAspectRatio="none" role="img" aria-label={`${label}. ${timeAxis}; ${amplitudeAxis}.`}><path className="wave-axis" d="M0 95H760"/><path className="wave-line" d={d}/><text x="0" y="214" className="wave-tick">0</text><text x="365" y="214" className="wave-tick">0.007</text><text x="715" y="214" className="wave-tick">0.014</text></svg><span className="wave-x-label">{timeAxis}</span></div></div>
}

export default function WaveLab({onBack}:{onBack:()=>void}){
 const[locale,setLocale]=useState<Locale>('en');const[frequency,setFrequency]=useState(200);const[soundSpeed,setSoundSpeed]=useState(1500);const[phase,setPhase]=useState(0);const[amplitude,setAmplitude]=useState(1);const[data,setData]=useState<WaveResponse|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState(false);const[retryNonce,setRetryNonce]=useState(0);const t=copy[locale];
 useEffect(()=>{const controller=new AbortController();const timer=window.setTimeout(async()=>{setLoading(true);setError(false);try{const displayCycles=frequency*TIME_WINDOW_MS;const r=await fetch(`${API_BASE}/api/v1/pedagogical/wave-kinematics`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({frequency_khz:frequency,sound_speed_mps:soundSpeed,normalized_amplitude:amplitude,initial_phase_rad:phase,sample_count:640,display_cycles:displayCycles,snapshot_time_fraction_of_period:0}),signal:controller.signal});if(!r.ok)throw new Error(String(r.status));setData(await r.json())}catch(e){if((e as Error).name!=='AbortError')setError(true)}finally{setLoading(false)}},100);return()=>{controller.abort();window.clearTimeout(timer)}},[frequency,soundSpeed,phase,amplitude,retryNonce]);
 const reset=()=>{setFrequency(200);setSoundSpeed(1500);setPhase(0);setAmplitude(1)};
 return <main className="wave-lab"><header className="wave-toolbar"><button onClick={onBack}>{t.back}</button><span>HydroSIM / PED-D1</span><div><button className={locale==='en'?'active':''} onClick={()=>setLocale('en')}>EN</button><button className={locale==='pt-BR'?'active':''} onClick={()=>setLocale('pt-BR')}>PT-BR</button></div></header><section className="wave-question"><span>{t.kicker}</span><h1>{t.title}</h1></section><div className="wave-layout"><aside className="wave-controls"><div className="wave-control-title"><Activity size={17}/><strong>{t.configured}</strong></div><label>{t.frequency}<output>{frequency} kHz</output><input type="range" min="20" max="700" step="10" value={frequency} onChange={e=>setFrequency(+e.target.value)}/></label><label>{t.soundSpeed}<output>{soundSpeed} m/s</output><input type="range" min="1400" max="1600" step="5" value={soundSpeed} onChange={e=>setSoundSpeed(+e.target.value)}/></label><label>{t.amplitude}<output>{amplitude.toFixed(1)}</output><input type="range" min="0" max="1" step="0.1" value={amplitude} onChange={e=>setAmplitude(+e.target.value)}/></label><label>{t.phase}<output>{phase.toFixed(2)} rad</output><input type="range" min="-3.14" max="3.14" step="0.1" value={phase} onChange={e=>setPhase(+e.target.value)}/></label><button className="wave-reset" onClick={reset}><RotateCcw size={15}/>{t.reset}</button>{loading&&<small className="wave-status">{t.updating}</small>}{error&&<button className="wave-error" onClick={()=>setRetryNonce(v=>v+1)}>{t.unavailable} · {t.retry}</button>}</aside><section className="wave-stage"><div className="wave-cause-strip"><div><small>{t.configured}</small><strong>{frequency} kHz</strong><span>f</span></div><i>→</i><div><small>{t.derived}</small><strong>{data?(data.period_seconds*1e6).toFixed(2):'—'} µs</strong><span>{t.period}</span></div><i>→</i><div><small>{t.derived}</small><strong>{data?data.wavelength_m.toFixed(4):'—'} m</strong><span>{t.wavelength}</span></div></div><div className="wave-canvas"><Trace series={data?.temporal_waveform} label={t.time} timeAxis={t.timeAxis} amplitudeAxis={t.amplitudeAxis}/></div></section></div></main>
}
